In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("~/Desktop/data.xls",header = 3)

In [3]:
data.head(5)

Unnamed: 0        Unnamed: 1  Unnamed: 2  Unnamed: 3 Глюкоза Мочевина  \
0         NaN               NaN         NaN         NaN    мМ/Л     мМ/Л   
1         2.0      Сл-сантехник         2.0      1956.0     6.2      5.9   
2         3.0          инженер          1.0      1962.0     5.2        5   
3         4.0  Инженер-технолог     -1000.0      1962.0     5.1      5.8   
4         5.0          водитель         2.0      1964.0     5.6      5.7   

  Креатинин Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
0     мкМ/Л        мкМ/Л       мМ/Л   мМ/Л  ...                           NaN   
1       110          443        6.2   1.07  ...                           NaN   
2        72          164        5.5   2.27  ...                           NaN   
3        85          345        6.6    2.1  ...                           NaN   
4        74          438        6.3   1.04  ...                          0.38   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
0                      NaN                    NaN         NaN        NaN   
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                  458.4         NaN     1600.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
0           NaN      NaN           NaN         NaN         NaN  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  

[5 rows x 37 columns]

In [4]:
data = data.drop(0)

In [5]:
data = data.rename(columns={"Unnamed: 0" : "Number", "Unnamed: 1" : "Profession"})
data = data.rename(columns={"Unnamed: 2" : "Gender", "Unnamed: 3" : "Birth_year"})

In [6]:
data.head(5)

Number        Profession  Gender  Birth_year Глюкоза Мочевина Креатинин  \
1     2.0      Сл-сантехник     2.0      1956.0     6.2      5.9       110   
2     3.0          инженер      1.0      1962.0     5.2        5        72   
3     4.0  Инженер-технолог -1000.0      1962.0     5.1      5.8        85   
4     5.0          водитель     2.0      1964.0     5.6      5.7        74   
5    12.0          слесарь      2.0      1959.0     5.7      5.5        88   

  Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
1          443        6.2   1.07  ...                           NaN   
2          164        5.5   2.27  ...                           NaN   
3          345        6.6    2.1  ...                           NaN   
4          438        6.3   1.04  ...                          0.38   
5          286        7.1   0.91  ...                          0.00   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                 458.40         NaN     1600.0   
5                     0.32                  70.91       120.0      400.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  
5         400.0    600.0         100.0           0        12.0  

[5 rows x 37 columns]

Profession - я не думаю, что от этого столбца в первоначальном виде будет большой смысл, но и в том виде, что делал я - смысла мало

Необходимо придумать способ разбить на меньшее число столбцов, которые имеют больше смысла.

Пока что идеей будет будет разделение на умственную напряженность и физическую напряженность по шкале от 0 до 1-3

In [8]:
data["Profession"].unique()

array(['Сл-сантехник', 'инженер ', 'Инженер-технолог', 'водитель',
       'слесарь ', 'изолировщица', 'аппаратчик', 'тракторист',
       'горничная', 'плавильщик', 'инженер', 'токарь ', 'внс',
       'экономист ', 'нач группы ', 'нач сектора', 'гл инженер ',
       'контролер КПП', 'нач-к ПРБ', 'УВОЛЕНА', 'диспетчер',
       'оператор                    1962', 'вед,специалист',
       'пригот-ль р-ров', 'ПЕНСИОНЕР', 'монтажник РЭА', 'техник',
       'сборщик м-схем', 'наладчик', 'измеритель', 'машинист',
       'инженер-прогр,', 'нач-к тех,бюро', 'нач-к группы',
       'старший мастер', 'гальваник', nan, 'мастер отд работ1969',
       'науч. сотр', 'эл. сварщик', 'фрезеровщик', 'изолировщик ',
       'эл,сварщик', 'электромонтажник', 'дежурная', 'нач-к бюро ',
       'нач-к сектора', 'маляр', 'маляр-штукатур', 'УВОЛЕН', 'мастер ',
       'прессовщик', 'зам, нач-ка отд,', 'инженр', 'секретарь ',
       'электрик'], dtype=object)

Должности будут получать такие шкалы: Пусть правилом будет не больше 3

Уволенные, пенсионеры - 0 физической, 0 умственной <br>
Слесари, сантехники, маляры - 3 физической, 0 умственной <br>
Инженеры, мастера - 1 физической, 2 умственной <br>
Учёные - 0 физической, 3 умственной <br>
Рабочие, связанные с сложными станками и изобретательной работой - 2 физической, 1 умственной <br>
Водители, горничные, официанты, секретари - 1 физической, 1 умственной <br>

In [9]:
L_0_0 = ['УВОЛЕНА', 'ПЕНСИОНЕР', np.nan, 'УВОЛЕН']
L_3_0 = ['Сл-сантехник','слесарь ','пригот-ль р-ров', 'техник', 'маляр',
        'маляр-штукатур']
L_1_2 = ['инженер ', 'Инженер-технолог', 'аппаратчик',  'инженер', 'нач группы ',
        'нач сектора','гл инженер ', 'сборщик м-схем', 'нач-к группы', 'старший мастер',
        'нач-к сектора', 'мастер ','зам, нач-ка отд,','инженр']
L_0_3 = ['внс', 'экономист ', 'нач-к ПРБ', 'вед,специалист', 'инженер-прогр,', 
        'нач-к тех,бюро', 'науч. сотр','нач-к бюро ']
L_2_1 = ['изолировщица', 'плавильщик', 'токарь ',  'оператор                    1962', 
        'монтажник РЭА', 'наладчик',  'измеритель', 'гальваник',  'мастер отд работ1969',
        'эл. сварщик', 'фрезеровщик', 'изолировщик ', 'эл,сварщик', 'электромонтажник', 
        'прессовщик', 'электрик']
L_1_1 = ['водитель', 'тракторист', 'горничная', 'контролер КПП', 'диспетчер', 'машинист', 
        'дежурная','секретарь ']

In [44]:
arr = np.array(data["Profession"])
phys = np.zeros(arr.__len__()).astype(int)
mind = np.zeros(arr.__len__()).astype(int)

In [45]:
for enum, i in enumerate(arr):
    if i in L_3_0:
        phys[enum] = 3
    
    if i in L_1_2:
        phys[enum] = 1
        mind[enum] = 2
    
    if i in L_0_3:
        mind[enum] = 3
    
    if i in L_2_1:
        phys[enum] = 2
        mind[enum] = 1
        
    if i in L_1_1:
        phys[enum] = 1
        mind[enum] = 1

In [46]:
data["phys"] = phys
data["mind"] = mind

In [47]:
np.unique(data["phys"])

array([0, 1, 2, 3])

In [48]:
data.drop(columns = ["Profession"], inplace = True)

Запишем в данные возраст вместо года рождения. М.б. потом преобразую в группу категориальных признаков по их возрасту: (к примеру) 0-18, 19-30, 31-45, 45-65, 65+

In [49]:
data["age"] = 2019 - data["Birth_year"]
data = data.drop(columns = {'Birth_year'})
data.head(1)

Number  Gender Глюкоза Мочевина Креатинин Мочевая к-та Холестерин Х-ЛПВП  \
1     2.0     2.0     6.2      5.9       110          443        6.2   1.07   

  Х-ЛПНП Триглицериды  ... HLDF (нг/мл АТ к S100b АТ к Анг  II  АТ к ЭТ   \
1   4.25         2.37  ...         NaN        NaN           NaN      NaN   

  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36 phys mind   age  
1           NaN           0         2.0    3    0  63.0  

[1 rows x 38 columns]

Фикс неточностей в данных

In [50]:
data['ГЛЖ ин Соколова-Лайона'].replace({"нет" : np.NaN, "да" : np.NaN}, inplace = True)

In [51]:
data.replace({"нет" : 0, "да" : 1, "нет " : 0, "да " : 1, "не" : 0}, inplace = True)

In [52]:
data.rename(columns={'курк\ение' : 'smoking', 'избыт, Потр, Алкоголя' : 'Alcoholic'}, inplace=True)

In [53]:
data['smoking'].replace({'нет нет' : 0}, inplace = True)
data['smoking'].unique(), data['smoking'].dtype

(array([1, 0]), dtype('int64'))

In [54]:
data['Alcoholic'].replace({'нет нет нет нет нет ' : 0, "нет  нет нет" : 0}, inplace = True)
data['Alcoholic'].unique(), data['Alcoholic'].dtype

(array([0, 1]), dtype('int64'))

In [55]:
data.rename(columns={'и,п повар, Соли' : 'excess_salt_consumption'}, inplace = True)
data['excess_salt_consumption'].unique()

array([0, 1])

In [56]:
data['гиподинамия'].replace({'нетт' : 0}, inplace = True)
data["гиподинамия"].unique(), data['гиподинамия'].dtype

(array([0, 1]), dtype('int64'))

In [57]:
data.replace({'уволил' : 6.0}, inplace = True)

In [58]:
data['индекс массы тела'].unique()

array([20, 20.69, 30.47, 31.8, 26.5, 40.2, 23.9, 41.03, 32.5, 21.5, 30.07,
       24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44, 19.89, 22.86,
       31.56, 25.5, 27.89, 29.4, 17.65, 29.05, 23.08, 45.3, 38.37, 23.12,
       25.46, 29.04, 24.68, 28.93, 27.14, 23.67, 29.31, 29.17, 27.44,
       26.22, 23.31, 27.66, 25.28, 23.44, '21, 08', 21.88, '26, 47', 24.8,
       18.78, 34.05, 20.28, 32, 48.33, 32.27, 21.64, 28.4, 27.87, 24.1,
       29.58, 33.08, 43.7, 28.08, 26.47, 22.84, 25.53, 23.14, 23.23, 22.3,
       40.16, 35.8, 26.85, 33.02, 23.05, 28.03, 28.41, 27.04, 38.74,
       28.34, 29.68, 24.6, 29.76, 27.68, 27.97, 27.12, 33.21, 39.92,
       25.16, 33.39, 31.23, '25, 04', 34.21, 49.08, 23.66, 24.16, 23.42,
       32.18, 25.84, 32.6, 26.9, 24.22, 22.34, 24.45, 27.24, 31.14, 22.03,
       36.06, 22.92, 24.54, 23.72, 29.07, 33.75, 19.14, 30.86, 27.09,
       25.03], dtype=object)

In [59]:
help_array = np.empty(len(data))

In [60]:
for enum, item in enumerate(data['индекс массы тела']):
    if type(item) == str:
        sub_str = item[0:2] + "." + item[4:]
        sub_float = float(sub_str)
        print(sub_float, type(sub_float))
        help_array[enum] = sub_float
        
    else:
        help_array[enum] = item

21.08 <class 'float'>
26.47 <class 'float'>
25.04 <class 'float'>


In [61]:
data['индекс массы тела'] = help_array

In [63]:
data['индекс массы тела'].unique()

array([20.  , 20.69, 30.47, 31.8 , 26.5 , 40.2 , 23.9 , 41.03, 32.5 ,
       21.5 , 30.07, 24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44,
       19.89, 22.86, 31.56, 25.5 , 27.89, 29.4 , 17.65, 29.05, 23.08,
       45.3 , 38.37, 23.12, 25.46, 29.04, 24.68, 28.93, 27.14, 23.67,
       29.31, 29.17, 27.44, 26.22, 23.31, 27.66, 25.28, 23.44, 21.08,
       21.88, 26.47, 24.8 , 18.78, 34.05, 20.28, 32.  , 48.33, 32.27,
       21.64, 28.4 , 27.87, 24.1 , 29.58, 33.08, 43.7 , 28.08, 22.84,
       25.53, 23.14, 23.23, 22.3 , 40.16, 35.8 , 26.85, 33.02, 23.05,
       28.03, 28.41, 27.04, 38.74, 28.34, 29.68, 24.6 , 29.76, 27.68,
       27.97, 27.12, 33.21, 39.92, 25.16, 33.39, 31.23, 25.04, 34.21,
       49.08, 23.66, 24.16, 23.42, 32.18, 25.84, 32.6 , 26.9 , 24.22,
       22.34, 24.45, 27.24, 31.14, 22.03, 36.06, 22.92, 24.54, 23.72,
       29.07, 33.75, 19.14, 30.86, 27.09, 25.03])

Необходимо подумать, что сделать с записью об инфаркте. Пока что придам ей уникальную метку

In [64]:
data['S100b, нг/л (N до 90)'].replace({'ИНФАРКТ МОЗГА В 2018 ГОДУ' : -1}, inplace = True)

Дублируемый столбец

In [66]:
data = data.drop(columns={"Unnamed: 36"})

Это наша цель

In [67]:
data = data.rename(columns={"Unnamed: 35" : "Target"})

In [68]:
data["Target"].unique()

array([0, 'о', 'п'], dtype=object)

In [69]:
data["Target"].replace({0 : 'о'}, inplace = True)

И определимся с полом

In [70]:
data["male"] = (data["Gender"] == 2).astype(int)
data["female"] = (data["Gender"] == 1).astype(int)
data["no_spec_gender"] = (data["Gender"] == -1000).astype(int)
data = data.drop(columns={"Gender"})

### Предварительный итог:

In [71]:
data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  АТ к Анг  II   АТ к ЭТ   \
1    4.25          2.37              20.00  ...            NaN       NaN   
2    3.39          0.64              20.69  ...            NaN       NaN   
3    4.14          0.36              30.47  ...            NaN       NaN   
4    3.96          3.38              31.80  ...         1600.0     400.0   
5    5.33          1.80              26.50  ...          400.0     600.0   

   АТ к HLDF- 24  Target  phys  mind   age  male  female  no_spec_gender  
1            NaN       о     3     0  63.0     1       0               0  
2            NaN       о     1     2  57.0     0       1               0  
3            NaN       о     1     2  57.0     0       0               1  
4           50.0       о     1     1  55.0     1       0               0  
5          100.0       о     3     0  60.0     1       0               0  

[5 rows x 39 columns]

Это, конечно, вкусовщина, но я переделаю классы в Target под +1 -1

In [72]:
data["Target"].replace({'о' : -1, 'п' : 1}, inplace = True)

### Итог преобразований:

In [73]:
data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  АТ к Анг  II   АТ к ЭТ   \
1    4.25          2.37              20.00  ...            NaN       NaN   
2    3.39          0.64              20.69  ...            NaN       NaN   
3    4.14          0.36              30.47  ...            NaN       NaN   
4    3.96          3.38              31.80  ...         1600.0     400.0   
5    5.33          1.80              26.50  ...          400.0     600.0   

   АТ к HLDF- 24  Target  phys  mind   age  male  female  no_spec_gender  
1            NaN      -1     3     0  63.0     1       0               0  
2            NaN      -1     1     2  57.0     0       1               0  
3            NaN      -1     1     2  57.0     0       0               1  
4           50.0      -1     1     1  55.0     1       0               0  
5          100.0      -1     3     0  60.0     1       0               0  

[5 rows x 39 columns]

In [76]:
data.to_csv("Data_transformed.csv", index=False)