In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("~/Desktop/data.xls",header = 3)

In [3]:
data.head(5)

Unnamed: 0        Unnamed: 1  Unnamed: 2  Unnamed: 3 Глюкоза Мочевина  \
0         NaN               NaN         NaN         NaN    мМ/Л     мМ/Л   
1         2.0      Сл-сантехник         2.0      1956.0     6.2      5.9   
2         3.0          инженер          1.0      1962.0     5.2        5   
3         4.0  Инженер-технолог     -1000.0      1962.0     5.1      5.8   
4         5.0          водитель         2.0      1964.0     5.6      5.7   

  Креатинин Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
0     мкМ/Л        мкМ/Л       мМ/Л   мМ/Л  ...                           NaN   
1       110          443        6.2   1.07  ...                           NaN   
2        72          164        5.5   2.27  ...                           NaN   
3        85          345        6.6    2.1  ...                           NaN   
4        74          438        6.3   1.04  ...                          0.38   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
0                      NaN                    NaN         NaN        NaN   
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                  458.4         NaN     1600.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
0           NaN      NaN           NaN         NaN         NaN  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  

[5 rows x 37 columns]

In [4]:
data = data.drop(0)

In [5]:
data = data.rename(columns={"Unnamed: 0" : "Number", "Unnamed: 1" : "Profession"})
data = data.rename(columns={"Unnamed: 2" : "Gender", "Unnamed: 3" : "Birth_year"})

In [6]:
data.head(5)

Number        Profession  Gender  Birth_year Глюкоза Мочевина Креатинин  \
1     2.0      Сл-сантехник     2.0      1956.0     6.2      5.9       110   
2     3.0          инженер      1.0      1962.0     5.2        5        72   
3     4.0  Инженер-технолог -1000.0      1962.0     5.1      5.8        85   
4     5.0          водитель     2.0      1964.0     5.6      5.7        74   
5    12.0          слесарь      2.0      1959.0     5.7      5.5        88   

  Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
1          443        6.2   1.07  ...                           NaN   
2          164        5.5   2.27  ...                           NaN   
3          345        6.6    2.1  ...                           NaN   
4          438        6.3   1.04  ...                          0.38   
5          286        7.1   0.91  ...                          0.00   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                 458.40         NaN     1600.0   
5                     0.32                  70.91       120.0      400.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  
5         400.0    600.0         100.0           0        12.0  

[5 rows x 37 columns]

In [7]:
data.columns

Index(['Number', 'Profession', 'Gender', 'Birth_year', 'Глюкоза', 'Мочевина',
       'Креатинин', 'Мочевая к-та', 'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП',
       'Триглицериды', 'индекс массы тела', 'курк\ение',
       'избыт, Потр, Алкоголя', 'и,п повар, Соли', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб', 'САД', 'ДАД',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='object')

In [8]:
data['Unnamed: 35'].unique()

array([0, 'о', 'п'], dtype=object)

In [9]:
(data["Unnamed: 36"] - data["Number"]).unique()
# the last column copies "Number" one, so i'd remove it as redundant

array([0.])

In [10]:
data = data.drop(columns={"Unnamed: 36"}, inplace=True)

In [11]:
data["Gender"].unique()
# okay, gender is 1 = female, 2 = male, -1000 - unknown

array([    2.,     1., -1000.])

In [12]:
data["male"] = (data["Gender"] == 2).astype(int)
data["female"] = (data["Gender"] == 1).astype(int)
data["no_spec_gender"] = (data["Gender"] == -1000).astype(int)
data = data.drop(columns={"Gender"})

In [13]:
data["Profession"].unique()
# I'd have to fix some issues with data

array(['Сл-сантехник', 'инженер ', 'Инженер-технолог', 'водитель',
       'слесарь ', 'изолировщица', 'аппаратчик', 'тракторист',
       'горничная', 'плавильщик', 'инженер', 'токарь ', 'внс',
       'экономист ', 'нач группы ', 'нач сектора', 'гл инженер ',
       'контролер КПП', 'нач-к ПРБ', 'УВОЛЕНА', 'диспетчер',
       'оператор                    1962', 'вед,специалист',
       'пригот-ль р-ров', 'ПЕНСИОНЕР', 'монтажник РЭА', 'техник',
       'сборщик м-схем', 'наладчик', 'измеритель', 'машинист',
       'инженер-прогр,', 'нач-к тех,бюро', 'нач-к группы',
       'старший мастер', 'гальваник', nan, 'мастер отд работ1969',
       'науч. сотр', 'эл. сварщик', 'фрезеровщик', 'изолировщик ',
       'эл,сварщик', 'электромонтажник', 'дежурная', 'нач-к бюро ',
       'нач-к сектора', 'маляр', 'маляр-штукатур', 'УВОЛЕН', 'мастер ',
       'прессовщик', 'зам, нач-ка отд,', 'инженр', 'секретарь ',
       'электрик'], dtype=object)

In [14]:
data["Profession"].replace({"инженер " : "инженер", "инженр" : "инженер", "мастер " : "мастер"}, inplace=True)
data["Profession"].fillna("no_info", inplace=True)

In [15]:
#laborers - ручная работа
#servants - обсл. состав
#leadership - управление
#scientific - научные специальности, работа мозгом
#engineering - инж. специальности
#no_data - без инфы
#retiree - пенсионер
data['laborers'] = data['Profession'] == 'Сл-сантехник' 
data['laborers'] |=                    data['Profession'] == 'водитель' 
data['laborers'] |=                    data['Profession'] == 'слесарь ' 
data['laborers'] |=                    data['Profession'] == 'изолировщица' 
data['laborers'] |=                    data['Profession'] == 'аппаратчик' 
data['laborers'] |=                    data['Profession'] == 'тракторист' 
data['laborers'] |=                    data['Profession'] == 'плавильщик' 
data['laborers'] |=                    data['Profession'] == 'токарь ' 
data['laborers'] |=                    data['Profession'] == 'оператор                    1962' 
data['laborers'] |=                    data['Profession'] == 'пригот-ль р-ров' 
data['laborers'] |=                    data['Profession'] == 'монтажник РЭА' 
data['laborers'] |=                    data['Profession'] == 'техник' 
data['laborers'] |=                    data['Profession'] == 'сборщик м-схем'  
data['laborers'] |=                    data['Profession'] == 'машинист' 
data['laborers'] |=                    data['Profession'] == 'старший мастер' 
data['laborers'] |=                    data['Profession'] == 'гальваник' 
data['laborers'] |=                    data['Profession'] == 'мастер отд работ1969' 
data['laborers'] |=                    data['Profession'] == 'эл. сварщик' 
data['laborers'] |=                    data['Profession'] == 'фрезеровщик' 
data['laborers'] |=                    data['Profession'] == 'изолировщик ' 
data['laborers'] |=                    data['Profession'] == 'эл,сварщик' 
data['laborers'] |=                    data['Profession'] == 'электромонтажник' 
data['laborers'] |=                    data['Profession'] == 'маляр' 
data['laborers'] |=                    data['Profession'] == 'маляр-штукатур' 
data['laborers'] |=                    data['Profession'] == 'мастер' 
data['laborers'] |=                    data['Profession'] == 'прессовщик'
data['laborers'] |=                    data['Profession'] == 'электрик'

data['servants'] = data['Profession'] == 'горничная' 
data['servants'] |=                    data['Profession'] == 'контролер КПП' 
data['servants'] |=                    data['Profession'] == 'диспетчер' 
data['servants'] |=                    data['Profession'] == 'дежурная' 
data['servants'] |=                    data['Profession'] == 'секретарь '

data['leadership'] = data['Profession'] == 'нач группы ' 
data['leadership'] |=                     data['Profession'] == 'нач сектора' 
data['leadership'] |=                       data['Profession'] == 'гл инженер ' 
data['leadership'] |=                      data['Profession'] == 'нач-к ПРБ' 
data['leadership'] |=                      data['Profession'] == 'нач-к тех,бюро' 
data['leadership'] |=                      data['Profession'] == 'нач-к группы' 
data['leadership'] |=                      data['Profession'] == 'старший мастер' 
data['leadership'] |=                      data['Profession'] == 'нач-к бюро ' 
data['leadership'] |=                      data['Profession'] == 'нач-к сектора' 
data['leadership'] |=                      data['Profession'] == 'мастер'
data['leadership'] |=                     data['Profession'] == 'зам, нач-ка отд,'

data['scientific'] = data['Profession'] == 'внс' 
data['scientific'] |=                      data['Profession'] == 'вед,специалист'
data['scientific'] |=                      data['Profession'] == 'науч. сотр'
data['scientific'] |=                      data['Profession'] == 'нач-к тех,бюро'
data['scientific'] |=                      data['Profession'] == 'нач-к бюро '
data['scientific'] |=                      data['Profession'] == 'экономист '

data['engineering'] = data['Profession'] == 'инженер'
data['engineering'] |= data['Profession'] == 'Инженер-технолог' 
data['engineering'] |= data['Profession'] == 'гл инженер '
data['engineering'] |= data['Profession'] == 'наладчик' 
data['engineering'] |= data['Profession'] == 'измеритель' 
data['engineering'] |= data['Profession'] == 'инженер-прогр,'
data['engineering'] |= data['Profession'] == 'нач-к тех,бюро'

data['no_job_data'] = data['Profession'] == 'no_info'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕНА'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕН'

data['retiree'] = data['Profession'] == 'ПЕНСИОНЕР'

In [16]:
data['laborers'] = data['laborers'].astype(int)
data['servants'] = data['servants'].astype(int)
data['leadership'] = data['leadership'].astype(int)
data['scientific'] = data['scientific'].astype(int)
data['engineering'] = data['engineering'].astype(int)
data['no_job_data'] = data['no_job_data'].astype(int)
data['retiree'] = data['retiree'].astype(int)

In [17]:
data.head(10)

Number        Profession  Birth_year Глюкоза Мочевина Креатинин  \
1      2.0      Сл-сантехник      1956.0     6.2      5.9       110   
2      3.0           инженер      1962.0     5.2        5        72   
3      4.0  Инженер-технолог      1962.0     5.1      5.8        85   
4      5.0          водитель      1964.0     5.6      5.7        74   
5     12.0          слесарь       1959.0     5.7      5.5        88   
6     15.0      изолировщица      1966.0    11.7      3.2        66   
7     16.0        аппаратчик      1974.0     5.4      3.8       105   
8     20.0          слесарь       1962.0     7.1      5.3        93   
9     22.0        тракторист      1968.0     7.3      5.2        73   
10    25.0         горничная      1976.0     5.3        4        73   

   Мочевая к-та Холестерин Х-ЛПВП Х-ЛПНП  ... male female no_spec_gender  \
1           443        6.2   1.07   4.25  ...    1      0              0   
2           164        5.5   2.27   3.39  ...    0      1              0   
3           345        6.6    2.1   4.14  ...    0      0              1   
4           438        6.3   1.04   3.96  ...    1      0              0   
5           286        7.1   0.91   5.33  ...    1      0              0   
6           434        6.8   0.92   4.59  ...    0      1              0   
7           437          6   1.64    3.5  ...    0      0              1   
8           478          4   0.53   1.73  ...    0      0              1   
9           409        5.4   1.38    3.8  ...    0      0              1   
10          276        5.5   2.56    0.7  ...    0      1              0   

   laborers servants leadership scientific engineering no_job_data retiree  
1         1        0          0          0           0           0       0  
2         0        0          0          0           1           0       0  
3         0        0          0          0           1           0       0  
4         1        0          0          0           0           0       0  
5         1        0          0          0           0           0       0  
6         1        0          0          0           0           0       0  
7         1        0          0          0           0           0       0  
8         1        0          0          0           0           0       0  
9         1        0          0          0           0           0       0  
10        0        1          0          0           0           0       0  

[10 rows x 45 columns]

In [18]:
# okay, now we can drop Profession column
data = data.drop(columns={'Profession'})

In [19]:
data.head(1)

Number  Birth_year Глюкоза Мочевина Креатинин Мочевая к-та Холестерин  \
1     2.0      1956.0     6.2      5.9       110          443        6.2   

  Х-ЛПВП Х-ЛПНП Триглицериды  ... male female no_spec_gender laborers  \
1   1.07   4.25         2.37  ...    1      0              0        1   

  servants leadership scientific engineering no_job_data retiree  
1        0          0          0           0           0       0  

[1 rows x 44 columns]

In [20]:
# i'd better keep age parameter instead of Birth_year one, let's say this'd be up to 2019
data["age"] = 2019 - data["Birth_year"]
data = data.drop(columns = {'Birth_year'})
data.head(1)

Number Глюкоза Мочевина Креатинин Мочевая к-та Холестерин Х-ЛПВП Х-ЛПНП  \
1     2.0     6.2      5.9       110          443        6.2   1.07   4.25   

  Триглицериды индекс массы тела  ... female no_spec_gender laborers servants  \
1         2.37                20  ...      0              0        1        0   

  leadership scientific engineering no_job_data retiree   age  
1          0          0           0           0       0  63.0  

[1 rows x 44 columns]

In [21]:
data.head(10)

Number Глюкоза Мочевина Креатинин Мочевая к-та Холестерин Х-ЛПВП Х-ЛПНП  \
1      2.0     6.2      5.9       110          443        6.2   1.07   4.25   
2      3.0     5.2        5        72          164        5.5   2.27   3.39   
3      4.0     5.1      5.8        85          345        6.6    2.1   4.14   
4      5.0     5.6      5.7        74          438        6.3   1.04   3.96   
5     12.0     5.7      5.5        88          286        7.1   0.91   5.33   
6     15.0    11.7      3.2        66          434        6.8   0.92   4.59   
7     16.0     5.4      3.8       105          437          6   1.64    3.5   
8     20.0     7.1      5.3        93          478          4   0.53   1.73   
9     22.0     7.3      5.2        73          409        5.4   1.38    3.8   
10    25.0     5.3        4        73          276        5.5   2.56    0.7   

   Триглицериды индекс массы тела  ... female no_spec_gender laborers  \
1          2.37                20  ...      0              0        1   
2          0.64             20.69  ...      1              0        0   
3          0.36             30.47  ...      0              1        0   
4          3.38              31.8  ...      0              0        1   
5           1.8              26.5  ...      0              0        1   
6          4.65              40.2  ...      1              0        1   
7           1.7              23.9  ...      0              1        1   
8          4.41             41.03  ...      0              1        1   
9          0.66              32.5  ...      0              1        1   
10         0.59              21.5  ...      1              0        0   

   servants leadership scientific engineering no_job_data retiree   age  
1         0          0          0           0           0       0  63.0  
2         0          0          0           1           0       0  57.0  
3         0          0          0           1           0       0  57.0  
4         0          0          0           0           0       0  55.0  
5         0          0          0           0           0       0  60.0  
6         0          0          0           0           0       0  53.0  
7         0          0          0           0           0       0  45.0  
8         0          0          0           0           0       0  57.0  
9         0          0          0           0           0       0  51.0  
10        1          0          0           0           0       0  43.0  

[10 rows x 44 columns]

In [22]:
data['ГЛЖ ин Соколова-Лайона'].replace({"нет" : np.NaN, "да" : np.NaN}, inplace = True)

In [23]:
data.replace({"нет" : 0, "да" : 1, "нет " : 0, "да " : 1, "не" : 0}, inplace = True)

In [24]:
data.head(1)

Number Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0     6.2       5.9        110           443         6.2    1.07   

   Х-ЛПНП  Триглицериды индекс массы тела  ... female no_spec_gender  \
1    4.25          2.37                20  ...      0              0   

   laborers servants  leadership  scientific  engineering  no_job_data  \
1         1        0           0           0            0            0   

   retiree   age  
1        0  63.0  

[1 rows x 44 columns]

In [25]:
data.columns

Index(['Number', 'Глюкоза', 'Мочевина', 'Креатинин', 'Мочевая к-та',
       'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП', 'Триглицериды', 'индекс массы тела',
       'курк\ение', 'избыт, Потр, Алкоголя', 'и,п повар, Соли', 'гиподинамия',
       'стресс', 'прием п\щ контрац', 'насл отяг, По ГБ, ',
       'насл отяг, По ССЗ', 'насл отяг, По СД', 'насл, Отяг по почечн, Заб',
       'САД', 'ДАД', 'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'Unnamed: 35', 'male', 'female',
       'no_spec_gender', 'laborers', 'servants', 'leadership', 'scientific',
       'engineering', 'no_job_data', 'retiree', 'age'],
      dtype='object')

In [26]:
data.rename(columns={'курк\ение' : 'smoking', 'избыт, Потр, Алкоголя' : 'Alcoholic'}, inplace=True)

In [27]:
data.columns

Index(['Number', 'Глюкоза', 'Мочевина', 'Креатинин', 'Мочевая к-та',
       'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП', 'Триглицериды', 'индекс массы тела',
       'smoking', 'Alcoholic', 'и,п повар, Соли', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб', 'САД', 'ДАД',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'Unnamed: 35', 'male', 'female',
       'no_spec_gender', 'laborers', 'servants', 'leadership', 'scientific',
       'engineering', 'no_job_data', 'retiree', 'age'],
      dtype='object')

In [28]:
data['smoking'].unique()

array([1, 0, 'нет нет'], dtype=object)

In [29]:
data['smoking'].replace({'нет нет' : 0}, inplace = True)
data['smoking'].unique(), data['smoking'].dtype

(array([1, 0]), dtype('int64'))

In [30]:
data['Alcoholic'].unique()

array([0, 'нет нет нет нет нет ', 1, 'нет  нет нет'], dtype=object)

In [31]:
data['Alcoholic'].replace({'нет нет нет нет нет ' : 0, "нет  нет нет" : 0}, inplace = True)
data['Alcoholic'].unique(), data['Alcoholic'].dtype

(array([0, 1]), dtype('int64'))

In [32]:
data.rename(columns={'и,п повар, Соли' : 'excess_salt_intake'}, inplace = True)
data['excess_salt_intake'].unique()

array([0, 1])

In [33]:
data['гиподинамия'].unique()

array([0, 1, 'нетт'], dtype=object)

In [34]:
data['гиподинамия'].replace({'нетт' : 0}, inplace = True)
data["гиподинамия"].unique(), data['гиподинамия'].dtype

(array([0, 1]), dtype('int64'))

In [35]:
data['стресс'].unique()

array([0, 1])

In [36]:
data['прием п\щ контрац'].unique()

array([0, 1])

In [37]:
data['насл отяг, По ГБ, '].unique()

array([0, 1])

In [38]:
data['насл отяг, По ССЗ'].unique()

array([0, 1])

In [39]:
data['насл отяг, По СД'].unique()

array([0, 1])

In [40]:
data['насл, Отяг по почечн, Заб'].unique()

array([0, 1])

In [41]:
data['ГЛЖ ин Соколова-Лайона'].unique()

array([nan, 22., 14., 18., 24., 25., 27., 35., 30., 26., 28., 23., 29.,
       32., 38., 34., 37., 20., 11., 17., 39., 36., 33.])

In [42]:
data['Глюкоза'].unique()

array([6.2, 5.2, 5.1, 5.6, 5.7, 11.7, 5.4, 7.1, 7.3, 5.3, 5.9, 6.1, 6.7,
       4.9, 10.3, 6.6, 4.8, 6, 5, 'уволил', 7.6, 4.3, 5.5, 6.9, 4.5, 5.8,
       14.8, 15.8, 6.4, 6.3, 8.5, 12.5], dtype=object)

In [43]:
sub_data = data['Глюкоза']

In [44]:
sub_data.replace({'уволил' : np.NaN}, inplace = True)

In [45]:
sub_data.unique()

array([ 6.2,  5.2,  5.1,  5.6,  5.7, 11.7,  5.4,  7.1,  7.3,  5.3,  5.9,
        6.1,  6.7,  4.9, 10.3,  6.6,  4.8,  6. ,  5. ,  nan,  7.6,  4.3,
        5.5,  6.9,  4.5,  5.8, 14.8, 15.8,  6.4,  6.3,  8.5, 12.5])

In [46]:
sd_mean = sub_data.mean()

In [47]:
data['Глюкоза'].fillna(sd_mean, inplace = True)

In [48]:
data['Глюкоза'].unique()

array([ 6.2       ,  5.2       ,  5.1       ,  5.6       ,  5.7       ,
       11.7       ,  5.4       ,  7.1       ,  7.3       ,  5.3       ,
        5.9       ,  6.1       ,  6.7       ,  4.9       , 10.3       ,
        6.6       ,  4.8       ,  6.        ,  5.        ,  5.99210526,
        7.6       ,  4.3       ,  5.5       ,  6.9       ,  4.5       ,
        5.8       , 14.8       , 15.8       ,  6.4       ,  6.3       ,
        8.5       , 12.5       ])

In [49]:
data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37                20  ...       0               0   
2    3.39          0.64             20.69  ...       1               0   
3    4.14          0.36             30.47  ...       0               1   
4    3.96          3.38              31.8  ...       0               0   
5    5.33          1.80              26.5  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 44 columns]

In [50]:
data.rename(columns = {'Unnamed: 35' : 'target'}, inplace = True)

In [51]:
data['S100b, нг/л (N до 90)'].unique()

array([nan, 65.48, 80.17, 91.13, 120.7, 109.9, 88.01, 30.16, 60.97, 126.5,
       127.9, 28.56, 44.22, 97.85, 60.57, 35.71, 46.01, 66.91, 106.5,
       68.05, 32.28, 70.79, 30.11, 46.03, 27.35,
       'ИНФАРКТ МОЗГА В 2018 ГОДУ', 79.02, 81.96, 47.16, 97.64, 83.72,
       84.27, 43.62, 62.78, 116.6, 25.48, 92.44, 38.36, 36.72, 47.68, 545,
       37.35, 84.98, 81.57, 91.92, 69.45, 48.29, 90.84, 38.63, 62.43,
       98.91, 52.85, 34.72, 78.62, 27.49, 41.32, 42.42, 40.29],
      dtype=object)

In [52]:
data['S100b, нг/л (N до 90)'].replace({'ИНФАРКТ МОЗГА В 2018 ГОДУ' : np.NaN}, inplace = True)

In [53]:
data.dtypes
# I also have to check ИМТ

Number                           float64
Глюкоза                          float64
Мочевина                         float64
Креатинин                          int64
Мочевая к-та                       int64
Холестерин                       float64
Х-ЛПВП                           float64
Х-ЛПНП                           float64
Триглицериды                     float64
индекс массы тела                 object
smoking                            int64
Alcoholic                          int64
excess_salt_intake                 int64
гиподинамия                        int64
стресс                             int64
прием п\щ контрац                  int64
насл отяг, По ГБ,                  int64
насл отяг, По ССЗ                  int64
насл отяг, По СД                   int64
насл, Отяг по почечн, Заб          int64
САД                              float64
ДАД                              float64
ГЛЖ ин Соколова-Лайона           float64
S100b, нг/л (N до 90)            float64
Анг II, пг/мл (N

In [54]:
data['индекс массы тела'].unique()
# I see objects which are added incorrectly

array([20, 20.69, 30.47, 31.8, 26.5, 40.2, 23.9, 41.03, 32.5, 21.5, 30.07,
       24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44, 19.89, 22.86,
       31.56, 25.5, 27.89, 29.4, 17.65, 29.05, 23.08, 45.3, 38.37, 23.12,
       25.46, 29.04, 24.68, 28.93, 27.14, 23.67, 29.31, 29.17, 27.44,
       26.22, 23.31, 27.66, 25.28, 23.44, '21, 08', 21.88, '26, 47', 24.8,
       18.78, 34.05, 20.28, 32, 48.33, 32.27, 21.64, 28.4, 27.87, 24.1,
       29.58, 33.08, 43.7, 28.08, 26.47, 22.84, 25.53, 23.14, 23.23, 22.3,
       40.16, 35.8, 26.85, 33.02, 23.05, 28.03, 28.41, 27.04, 38.74,
       28.34, 29.68, 24.6, 29.76, 27.68, 27.97, 27.12, 33.21, 39.92,
       25.16, 33.39, 31.23, '25, 04', 34.21, 49.08, 23.66, 24.16, 23.42,
       32.18, 25.84, 32.6, 26.9, 24.22, 22.34, 24.45, 27.24, 31.14, 22.03,
       36.06, 22.92, 24.54, 23.72, 29.07, 33.75, 19.14, 30.86, 27.09,
       25.03], dtype=object)

In [55]:
help_array = np.empty(len(data))

In [56]:
for enum, item in enumerate(data['индекс массы тела']):
    if type(item) == str:
        sub_str = item[0:2] + "." + item[4:]
        sub_float = float(sub_str)
        print(sub_float, type(sub_float))
        help_array[enum] = sub_float
        
    else:
        help_array[enum] = item

21.08 <class 'float'>
26.47 <class 'float'>
25.04 <class 'float'>


In [57]:
help_array

array([20.  , 20.69, 30.47, 31.8 , 26.5 , 40.2 , 23.9 , 41.03, 32.5 ,
       21.5 , 30.07, 24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44,
       19.89, 22.86, 31.56, 25.5 , 27.89, 29.4 , 17.65, 29.05, 23.08,
       45.3 , 38.37, 23.12, 25.46, 29.04, 24.68, 28.93, 27.14, 23.67,
       29.31, 29.17, 27.44, 26.22, 23.31, 27.66, 25.28, 23.44, 21.08,
       21.88, 26.47, 24.8 , 18.78, 34.05, 20.28, 32.  , 48.33, 32.27,
       21.64, 28.4 , 27.87, 24.1 , 29.58, 33.08, 43.7 , 28.08, 26.47,
       22.84, 25.53, 23.14, 23.23, 22.3 , 40.16, 35.8 , 26.85, 33.02,
       23.05, 28.03, 28.41, 27.04, 38.74, 28.34, 29.68, 24.6 , 29.76,
       27.68, 27.97, 27.12, 33.21, 39.92, 25.16, 33.39, 31.23, 25.04,
       34.21, 49.08, 23.66, 24.16, 23.42, 32.18, 25.84, 32.6 , 26.9 ,
       24.22, 28.34, 22.34, 24.45, 27.24, 31.14, 22.03, 36.06, 22.92,
       24.54, 23.72, 29.07, 33.75, 26.47, 19.14, 30.86, 27.09, 25.03])

In [58]:
data['индекс массы тела'] = help_array

In [59]:
data['target'].unique()

array([0, 'о', 'п'], dtype=object)

In [60]:
sub_data = pd.DataFrame.copy(data)

In [61]:
sub_data.head(2)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   

   retiree   age  
1        0  63.0  
2        0  57.0  

[2 rows x 44 columns]

1 вариант

In [62]:
Index_label = sub_data[sub_data['target'] == 0].index.tolist()

In [63]:
test_set = sub_data.loc[Index_label].drop(columns = {'target'})

In [64]:
test_set.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 43 columns]

In [65]:
Anti_Index_label = sub_data[sub_data['target'] != 0].index.tolist()

In [66]:
train_set = sub_data.loc[Anti_Index_label].drop(columns = {'target'})
train_target = sub_data.loc[Anti_Index_label]['target']

In [67]:
train_set.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
61    64.0      5.4       6.3         57           174         4.7    1.59   
62   131.0      5.2       8.8         98           349         3.7    1.25   
63   135.0      6.0       6.5        102           403         4.8    0.84   
64   138.0      5.7       5.1         92           289         4.4    1.16   
65   144.0      5.1       5.1         57           255         5.0    1.37   

    Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
61    2.90          0.77              43.70  ...       1               0   
62    2.45          0.73              28.08  ...       0               0   
63    3.23          0.73              26.47  ...       0               0   
64    2.78          0.80              22.84  ...       0               0   
65    3.14          0.94              25.53  ...       1               0   

    laborers  servants  leadership  scientific  engineering  no_job_data  \
61         1         0           0           0            0            0   
62         0         0           0           0            0            1   
63         1         0           0           0            0            0   
64         1         0           0           0            0            0   
65         0         0           0           1            0            0   

    retiree   age  
61        0  46.0  
62        0  29.0  
63        0  50.0  
64        0  37.0  
65        0  45.0  

[5 rows x 43 columns]

In [68]:
from sklearn.ensemble import GradientBoostingClassifier as GBC

In [69]:
model = GBC(n_estimators = 300)

In [70]:
train_set.fillna(0, inplace = True)

In [71]:
model.fit(train_set, train_target)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=300,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [72]:
test_set.fillna(0, inplace = True)

In [73]:
pred_GBC_with = model.predict(test_set)

In [74]:
pred_GBC_with

array(['п', 'п', 'п', 'п', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о',
       'о', 'о', 'о', 'п', 'п', 'п', 'о', 'о', 'п', 'о', 'п', 'о', 'о',
       'п', 'п', 'п', 'п', 'о', 'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п',
       'п', 'о', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'о', 'п', 'п',
       'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п'], dtype=object)

вариант 2

In [75]:
sub_data['target'].replace({0 : 'о', 'o' : 'о'}, inplace = True)

In [76]:
sub_data['target'].unique()

array(['о', 'п'], dtype=object)

In [77]:
from sklearn.model_selection import StratifiedKFold

In [78]:
target = sub_data['target']
sub_data = sub_data.fillna(0)

In [79]:
sub_data.drop(columns={'target'}, inplace = True)

In [80]:
sub_data['ДАД']

1       90.0
2       80.0
3       80.0
4       80.0
5       80.0
       ...  
113     80.0
114     80.0
115     90.0
116    100.0
117     90.0
Name: ДАД, Length: 117, dtype: float64

In [81]:
folds = StratifiedKFold(n_splits = 8, shuffle = True, random_state = 317)

In [82]:
model = GBC(n_estimators = 300)

In [83]:
from sklearn.metrics import accuracy_score as ac_s

In [84]:
summed_with = 0

for train_split, test_split in folds.split(sub_data, target):
    
    #print(train_split, test_split)

    data_train, data_test = sub_data.loc[train_split + 1], sub_data.loc[test_split + 1]
    targ_train, targ_test = target.loc[train_split + 1], target.loc[test_split + 1]
    
    model.fit(data_train, targ_train)
    pred = model.predict(data_test)
    
    summed_with += ac_s(targ_test, pred)
    print("Accuracy: ", ac_s(targ_test, pred))
    
summed_with /= 8

Accuracy:  0.9375
Accuracy:  0.8125
Accuracy:  0.6666666666666666
Accuracy:  0.7857142857142857
Accuracy:  0.7857142857142857
Accuracy:  0.8571428571428571
Accuracy:  1.0
Accuracy:  0.7857142857142857


Теперь попробуем удалить столбцы давления

In [85]:
sub_data = pd.DataFrame.copy(data)
sub_data.drop(columns={'САД', 'ДАД'}, inplace = True)

In [86]:
sub_data.columns

Index(['Number', 'Глюкоза', 'Мочевина', 'Креатинин', 'Мочевая к-та',
       'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП', 'Триглицериды', 'индекс массы тела',
       'smoking', 'Alcoholic', 'excess_salt_intake', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target', 'male', 'female',
       'no_spec_gender', 'laborers', 'servants', 'leadership', 'scientific',
       'engineering', 'no_job_data', 'retiree', 'age'],
      dtype='object')

In [87]:
sub_data['target'].unique()

array([0, 'о', 'п'], dtype=object)

In [88]:
Index_label, Anti_Index_label

([1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60],
 [61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117])

In [89]:
target_col = pd.DataFrame.copy(sub_data['target'])
target_col

1      0
2      0
3      0
4      0
5      0
      ..
113    п
114    п
115    п
116    п
117    п
Name: target, Length: 117, dtype: object

In [90]:
sub_data.drop(columns = {'target'}, inplace = True)

In [91]:
data_train = sub_data.loc[Anti_Index_label]
data_test = sub_data.loc[Index_label]
target_train = target_col.loc[Anti_Index_label]

In [92]:
data_train.fillna(0, inplace = True)
data_test.fillna(0, inplace = True)

In [93]:
model.fit(data_train, target_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=300,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [94]:
pred_GBC_without = model.predict(data_test)

In [95]:
pred_GBC_without

array(['п', 'п', 'п', 'п', 'о', 'о', 'о', 'о', 'о', 'о', 'п', 'о', 'о',
       'о', 'о', 'о', 'п', 'п', 'п', 'о', 'о', 'п', 'о', 'п', 'о', 'о',
       'п', 'п', 'п', 'п', 'о', 'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п',
       'п', 'о', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'о', 'п', 'п',
       'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п'], dtype=object)

Для сравнения

In [96]:
pred_GBC_with

array(['п', 'п', 'п', 'п', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о', 'о',
       'о', 'о', 'о', 'п', 'п', 'п', 'о', 'о', 'п', 'о', 'п', 'о', 'о',
       'п', 'п', 'п', 'п', 'о', 'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п',
       'п', 'о', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'о', 'п', 'п',
       'о', 'о', 'п', 'п', 'о', 'п', 'п', 'п'], dtype=object)

Рассмотрим кросс-валидацию на тех же условиях

In [97]:
target_col.replace({0 : 'о', 'o' : 'о'}, inplace = True)
target_col.unique()

array(['о', 'п'], dtype=object)

In [98]:
sub_data.fillna(0, inplace = True)

In [99]:
summed_without = 0

for train_split, test_split in folds.split(sub_data, target_col):
    
    #print(train_split, test_split)
    
    data_train, data_test = sub_data.loc[train_split + 1], sub_data.loc[test_split + 1]
    targ_train, targ_test = target_col.loc[train_split + 1], target_col.loc[test_split + 1]
    
    model.fit(data_train, targ_train)
    pred = model.predict(data_test)
    summed_without += ac_s(targ_test, pred)
    print("Accuracy: ", ac_s(targ_test, pred))
    
summed_without /= 8

Accuracy:  0.6875
Accuracy:  0.625
Accuracy:  0.8
Accuracy:  0.7857142857142857
Accuracy:  0.7142857142857143
Accuracy:  0.7142857142857143
Accuracy:  0.9285714285714286
Accuracy:  0.7857142857142857


In [100]:
summed_with, summed_without

(0.8288690476190476, 0.7551339285714286)

Попробуем заменять np.NaN через mean

In [206]:
sub_data = pd.DataFrame.copy(data)

In [207]:
S100b_arr = np.array(sub_data['S100b, нг/л (N до 90)'])
mean = np.nanmean(S100b_arr)
mean

75.53298240423617

In [ ]:
for item in Index_label:
    

Теперь я попробую чуть логичнее заменять np.NaN

In [101]:
data

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1       2.0      6.2       5.9        110           443         6.2    1.07   
2       3.0      5.2       5.0         72           164         5.5    2.27   
3       4.0      5.1       5.8         85           345         6.6    2.10   
4       5.0      5.6       5.7         74           438         6.3    1.04   
5      12.0      5.7       5.5         88           286         7.1    0.91   
..      ...      ...       ...        ...           ...         ...     ...   
113   134.0      5.3       6.5         73           366         4.9    1.73   
114   137.0      5.4       6.4         92           420         6.2    1.79   
115   140.0      5.5       4.2         67           380         4.7    1.35   
116   141.0      5.5       4.1         90           321         4.7    0.80   
117   146.0      5.4       5.8         95           445         3.7    0.86   

     Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1      4.25          2.37              20.00  ...       0               0   
2      3.39          0.64              20.69  ...       1               0   
3      4.14          0.36              30.47  ...       0               1   
4      3.96          3.38              31.80  ...       0               0   
5      5.33          1.80              26.50  ...       0               0   
..      ...           ...                ...  ...     ...             ...   
113    3.14          0.75              26.47  ...       0               0   
114    3.79          1.23              19.14  ...       0               0   
115    3.15          0.93              30.86  ...       1               0   
116    2.07          1.79              27.09  ...       0               0   
117    2.20          2.14              25.03  ...       0               0   

     laborers  servants  leadership  scientific  engineering  no_job_data  \
1           1         0           0           0            0            0   
2           0         0           0           0            1            0   
3           0         0           0           0            1            0   
4           1         0           0           0            0            0   
5           1         0           0           0            0            0   
..        ...       ...         ...         ...          ...          ...   
113         0         0           0           0            1            0   
114         1         0           0           0            0            0   
115         0         1           0           0            0            0   
116         1         0           0           0            0            0   
117         1         0           0           0            0            0   

     retiree   age  
1          0  63.0  
2          0  57.0  
3          0  57.0  
4          0  55.0  
5          0  60.0  
..       ...   ...  
113        0  30.0  
114        0  39.0  
115        0  48.0  
116        0  42.0  
117        0  48.0  

[117 rows x 44 columns]

In [102]:
data.columns

Index(['Number', 'Глюкоза', 'Мочевина', 'Креатинин', 'Мочевая к-та',
       'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП', 'Триглицериды', 'индекс массы тела',
       'smoking', 'Alcoholic', 'excess_salt_intake', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб', 'САД', 'ДАД',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target', 'male', 'female',
       'no_spec_gender', 'laborers', 'servants', 'leadership', 'scientific',
       'engineering', 'no_job_data', 'retiree', 'age'],
      dtype='object')

In [103]:
data['ГЛЖ ин Соколова-Лайона'].unique()

array([nan, 22., 14., 18., 24., 25., 27., 35., 30., 26., 28., 23., 29.,
       32., 38., 34., 37., 20., 11., 17., 39., 36., 33.])

In [104]:
GLZ_arr = np.array(data['ГЛЖ ин Соколова-Лайона'])
GLZ_mean = np.nanmean(GLZ_arr)
GLZ_mean

26.660377358490567

In [105]:
data['ГЛЖ ин Соколова-Лайона'].fillna(GLZ_mean, inplace = True)
data['ГЛЖ ин Соколова-Лайона'].unique()

array([26.66037736, 22.        , 14.        , 18.        , 24.        ,
       25.        , 27.        , 35.        , 30.        , 26.        ,
       28.        , 23.        , 29.        , 32.        , 38.        ,
       34.        , 37.        , 20.        , 11.        , 17.        ,
       39.        , 36.        , 33.        ])

Попробуем сделать так: предскажем пустые данные через градиентный бустинг перед решением самой задачи

In [106]:
S100b_labels = data[data['S100b, нг/л (N до 90)'] < 10000].index.tolist()
S100b_labels

[4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 19,
 20,
 21,
 22,
 23,
 25,
 26,
 31,
 32,
 33,
 36,
 41,
 48,
 50,
 53,
 54,
 57,
 58,
 60,
 61,
 62,
 63,
 69,
 71,
 72,
 74,
 77,
 79,
 80,
 83,
 84,
 85,
 91,
 92,
 95,
 96,
 99,
 105,
 106,
 108,
 110,
 113]

In [107]:
S100b_anti_labels = []
for i in range(1, 118):
    S100b_anti_labels.append(i)
    
for item in S100b_labels:
    S100b_anti_labels.remove(item)
    
S100b_anti_labels

[1,
 2,
 3,
 18,
 24,
 27,
 28,
 29,
 30,
 34,
 35,
 37,
 38,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 49,
 51,
 52,
 55,
 56,
 59,
 64,
 65,
 66,
 67,
 68,
 70,
 73,
 75,
 76,
 78,
 81,
 82,
 86,
 87,
 88,
 89,
 90,
 93,
 94,
 97,
 98,
 100,
 101,
 102,
 103,
 104,
 107,
 109,
 111,
 112,
 114,
 115,
 116,
 117]

In [108]:
sub_data = pd.DataFrame.copy(data)

In [109]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 35 columns]

In [110]:
S100b_target = data['S100b, нг/л (N до 90)']

In [111]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = S100b_target.loc[S100b_anti_labels]
target_train = S100b_target.loc[S100b_labels]

In [112]:
data_train.drop(columns={'target'}, inplace = True)
target_train.drop(columns={'target'}, inplace = True)

In [113]:
from sklearn.ensemble import GradientBoostingRegressor as GBR

In [114]:
model_col = GBR(n_estimators = 300)

In [115]:
data_train.dtypes

Number                       float64
Глюкоза                      float64
Мочевина                     float64
Креатинин                      int64
Мочевая к-та                   int64
Холестерин                   float64
Х-ЛПВП                       float64
Х-ЛПНП                       float64
Триглицериды                 float64
индекс массы тела            float64
smoking                        int64
Alcoholic                      int64
excess_salt_intake             int64
гиподинамия                    int64
стресс                         int64
прием п\щ контрац              int64
насл отяг, По ГБ,              int64
насл отяг, По ССЗ              int64
насл отяг, По СД               int64
насл, Отяг по почечн, Заб      int64
САД                          float64
ДАД                          float64
ГЛЖ ин Соколова-Лайона       float64
male                           int64
female                         int64
no_spec_gender                 int64
laborers                       int64
s

In [116]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [117]:
data_test.drop(columns={'target'}, inplace = True)

In [118]:
preds = model_col.predict(data_test)
preds

array([ 81.62531373,  44.17553666,  94.10710318,  48.0186048 ,
        70.860788  ,  46.22012353,  78.22609969,  72.30949738,
        55.18759474,  82.73674638,  79.51865402,  70.80577478,
       120.37610517,  83.62358647,  43.06776868,  48.86137405,
        62.71019988,  71.79162489,  47.29773369,  35.7942228 ,
       381.40975654,  37.17918894,  71.69225192,  62.99793884,
        29.7725581 ,  76.8144188 ,  68.56598691,  40.30117522,
        54.87286572,  73.78325159,  41.85568777,  33.37535663,
        75.10285683,  44.97420334,  70.19885066, 119.65204761,
        81.64278347,  94.93225564,  56.08166622, 317.820121  ,
        46.34625476,  97.37554389,  87.20051289,  91.60908043,
        60.58246132,  57.50941238,  79.9194417 ,  83.07477957,
       107.06368084,  71.21404197,  44.32221319,  64.59196073,
        70.66052866,  56.49568514,  74.18449039,  43.87713042,
        85.48644977,  58.62355015,  68.16259722,  64.21226179,
        88.11718982])

In [119]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item,'S100b, нг/л (N до 90)'] = preds[i]
    i += 1

In [120]:
data['S100b, нг/л (N до 90)']

1      81.625314
2      44.175537
3      94.107103
4      65.480000
5      80.170000
         ...    
113    40.290000
114    58.623550
115    68.162597
116    64.212262
117    88.117190
Name: S100b, нг/л (N до 90), Length: 117, dtype: float64

In [121]:
data.dtypes

Number                           float64
Глюкоза                          float64
Мочевина                         float64
Креатинин                          int64
Мочевая к-та                       int64
Холестерин                       float64
Х-ЛПВП                           float64
Х-ЛПНП                           float64
Триглицериды                     float64
индекс массы тела                float64
smoking                            int64
Alcoholic                          int64
excess_salt_intake                 int64
гиподинамия                        int64
стресс                             int64
прием п\щ контрац                  int64
насл отяг, По ГБ,                  int64
насл отяг, По ССЗ                  int64
насл отяг, По СД                   int64
насл, Отяг по почечн, Заб          int64
САД                              float64
ДАД                              float64
ГЛЖ ин Соколова-Лайона           float64
S100b, нг/л (N до 90)            float64
Анг II, пг/мл (N

In [122]:
data

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1       2.0      6.2       5.9        110           443         6.2    1.07   
2       3.0      5.2       5.0         72           164         5.5    2.27   
3       4.0      5.1       5.8         85           345         6.6    2.10   
4       5.0      5.6       5.7         74           438         6.3    1.04   
5      12.0      5.7       5.5         88           286         7.1    0.91   
..      ...      ...       ...        ...           ...         ...     ...   
113   134.0      5.3       6.5         73           366         4.9    1.73   
114   137.0      5.4       6.4         92           420         6.2    1.79   
115   140.0      5.5       4.2         67           380         4.7    1.35   
116   141.0      5.5       4.1         90           321         4.7    0.80   
117   146.0      5.4       5.8         95           445         3.7    0.86   

     Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1      4.25          2.37              20.00  ...       0               0   
2      3.39          0.64              20.69  ...       1               0   
3      4.14          0.36              30.47  ...       0               1   
4      3.96          3.38              31.80  ...       0               0   
5      5.33          1.80              26.50  ...       0               0   
..      ...           ...                ...  ...     ...             ...   
113    3.14          0.75              26.47  ...       0               0   
114    3.79          1.23              19.14  ...       0               0   
115    3.15          0.93              30.86  ...       1               0   
116    2.07          1.79              27.09  ...       0               0   
117    2.20          2.14              25.03  ...       0               0   

     laborers  servants  leadership  scientific  engineering  no_job_data  \
1           1         0           0           0            0            0   
2           0         0           0           0            1            0   
3           0         0           0           0            1            0   
4           1         0           0           0            0            0   
5           1         0           0           0            0            0   
..        ...       ...         ...         ...          ...          ...   
113         0         0           0           0            1            0   
114         1         0           0           0            0            0   
115         0         1           0           0            0            0   
116         1         0           0           0            0            0   
117         1         0           0           0            0            0   

     retiree   age  
1          0  63.0  
2          0  57.0  
3          0  57.0  
4          0  55.0  
5          0  60.0  
..       ...   ...  
113        0  30.0  
114        0  39.0  
115        0  48.0  
116        0  42.0  
117        0  48.0  

[117 rows x 44 columns]

In [123]:
sub_data = pd.DataFrame.copy(data)

In [124]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [125]:
ANG_target = data['Анг II, пг/мл (N 10-60 пг/мл)']

In [126]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [127]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [128]:
preds = model_col.predict(data_test)

In [129]:
preds

array([ 5.24431118e+03,  1.08941153e+02, -1.50195448e+01,  1.90713011e+02,
        1.13033498e+02,  6.89477802e+01,  3.04238898e+01,  3.23238255e+01,
        6.54655853e+00,  1.09026153e+03,  3.83826802e+01,  9.36365301e+01,
        5.19876696e+01,  3.23837920e+01,  1.67768750e+01,  1.88782173e+01,
        1.56652492e+01,  6.37519910e-01,  4.25322307e+01,  1.08137992e+01,
        5.73896656e+01,  7.21929209e+01,  2.36679136e+01,  3.68371489e+01,
        6.19581315e+01,  2.46500018e+01,  3.06731545e+01,  2.46104103e+01,
        1.76255433e+02,  2.69885254e+01,  2.44153626e+01,  3.06842609e+01,
        1.57881599e+01,  2.67143331e+01,  8.20535255e+01,  2.62442854e+03,
       -1.32621205e+00,  3.20228227e+03,  6.36839767e+01,  3.03107147e+01,
        4.45626236e+01,  2.55464821e+01,  1.12475630e+03,  3.05218671e+01,
        1.39189620e+01,  4.65101669e+01,  8.84862653e+01,  3.15262899e+01,
       -7.59719672e+00,  2.63216164e+01,  1.92444238e+01,  1.41940447e+01,
        3.13334558e+01,  

In [130]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'Анг II, пг/мл (N 10-60 пг/мл)'] = preds[i]
    i += 1

In [131]:
data['Анг II, пг/мл (N 10-60 пг/мл)'].unique()

array([ 5.24431118e+03,  1.08941153e+02, -1.50195448e+01,  3.80000000e-01,
        0.00000000e+00,  1.46000000e+01,  4.16000000e+01,  1.27000000e+01,
        1.18800000e+01,  5.51000000e+00,  5.47200000e+03,  8.83000000e+00,
        4.70200000e+01,  1.49500000e+01,  4.92400000e+01,  1.90713011e+02,
        1.35000000e+02,  1.26200000e+01,  1.97700000e+01,  1.84000000e+01,
        2.92900000e+01,  1.13033498e+02,  1.43400000e+01,  1.14400000e+01,
        6.89477802e+01,  3.04238898e+01,  3.23238255e+01,  6.54655853e+00,
        4.53100000e+02,  1.99000000e+02,  1.30300000e+01,  1.09026153e+03,
        3.83826802e+01,  2.37800000e+01,  9.36365301e+01,  5.19876696e+01,
        3.23837920e+01,  1.67768750e+01,  3.02000000e+00,  1.88782173e+01,
        1.56652492e+01,  6.37519910e-01,  4.25322307e+01,  1.08137992e+01,
        5.73896656e+01,  1.05700000e+02,  7.21929209e+01,  3.14800000e+01,
        2.36679136e+01,  3.68371489e+01,  2.25100000e+03,  7.35100000e+01,
        6.19581315e+01,  

In [132]:
sub_data = pd.DataFrame.copy(data)

In [133]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [134]:
ANG_target = data['ЭТ, пмоль/л    (N =0,09)']

In [135]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [136]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [137]:
preds = model_col.predict(data_test)

In [138]:
preds

array([ 5.13708905e-01, -9.96317302e-03,  4.88368051e+00,  9.99638759e-04,
        3.22531409e-01,  8.57633489e-02,  2.21194216e-01, -2.70412902e-03,
        1.97756824e-01,  1.45307337e+00,  5.39476051e-01,  6.56169743e-02,
        3.14685942e-01,  3.66876266e-02, -3.15855183e-02,  2.81129896e-02,
        6.05114919e-03,  2.78971894e-01,  9.06656000e-02,  5.34138310e+00,
        1.96467323e-01,  1.65021234e-01,  8.12450467e-01,  9.69562151e-01,
        2.88386562e-01,  2.26182033e+00,  1.93069643e+00,  2.21883782e-01,
        1.26086720e+00,  1.24707731e+00,  1.21438418e-01,  7.41760065e-02,
        1.07546496e-01,  1.56538247e-01,  2.38769342e-02,  1.70254785e+00,
        4.44946500e-02,  2.87094734e-01,  5.24970803e-02,  5.79908547e-01,
       -5.94646808e-03,  4.41316313e-01,  1.78674839e+00,  6.35639333e-01,
        2.48151978e-01,  9.43435103e-01,  8.72701388e-01,  6.29138841e-01,
        7.52182647e-01,  3.36030865e-01,  2.81483999e-01,  1.31235670e+00,
        3.62645630e-01,  

In [139]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'ЭТ, пмоль/л    (N =0,09)'] = preds[i]
    i += 1

In [140]:
data

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1       2.0      6.2       5.9        110           443         6.2    1.07   
2       3.0      5.2       5.0         72           164         5.5    2.27   
3       4.0      5.1       5.8         85           345         6.6    2.10   
4       5.0      5.6       5.7         74           438         6.3    1.04   
5      12.0      5.7       5.5         88           286         7.1    0.91   
..      ...      ...       ...        ...           ...         ...     ...   
113   134.0      5.3       6.5         73           366         4.9    1.73   
114   137.0      5.4       6.4         92           420         6.2    1.79   
115   140.0      5.5       4.2         67           380         4.7    1.35   
116   141.0      5.5       4.1         90           321         4.7    0.80   
117   146.0      5.4       5.8         95           445         3.7    0.86   

     Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1      4.25          2.37              20.00  ...       0               0   
2      3.39          0.64              20.69  ...       1               0   
3      4.14          0.36              30.47  ...       0               1   
4      3.96          3.38              31.80  ...       0               0   
5      5.33          1.80              26.50  ...       0               0   
..      ...           ...                ...  ...     ...             ...   
113    3.14          0.75              26.47  ...       0               0   
114    3.79          1.23              19.14  ...       0               0   
115    3.15          0.93              30.86  ...       1               0   
116    2.07          1.79              27.09  ...       0               0   
117    2.20          2.14              25.03  ...       0               0   

     laborers  servants  leadership  scientific  engineering  no_job_data  \
1           1         0           0           0            0            0   
2           0         0           0           0            1            0   
3           0         0           0           0            1            0   
4           1         0           0           0            0            0   
5           1         0           0           0            0            0   
..        ...       ...         ...         ...          ...          ...   
113         0         0           0           0            1            0   
114         1         0           0           0            0            0   
115         0         1           0           0            0            0   
116         1         0           0           0            0            0   
117         1         0           0           0            0            0   

     retiree   age  
1          0  63.0  
2          0  57.0  
3          0  57.0  
4          0  55.0  
5          0  60.0  
..       ...   ...  
113        0  30.0  
114        0  39.0  
115        0  48.0  
116        0  42.0  
117        0  48.0  

[117 rows x 44 columns]

In [141]:
sub_data = pd.DataFrame.copy(data)

In [142]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [143]:
ANG_target = data['VEGF,  пг/мл (N40-600)']

In [144]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [145]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [146]:
preds = model_col.predict(data_test)

In [147]:
preds

array([127.08574153,  75.43744143, 368.1529663 , 132.88233154,
       417.41301196, 278.1837496 , 499.99084601, 378.96390944,
       289.15725357, 631.41088496, 499.62855721, 325.0596398 ,
       377.69574302, 371.76535279, 374.88222206, 300.66937568,
       279.3588434 , 359.69947625, 226.17082759, 207.83636578,
       886.07606658, 296.35677722, 213.53322105, 281.44847677,
       161.29745968, 324.94932193, 578.51484244, 192.96963374,
       283.90978036, 251.96297063, 139.98959361, 221.4274331 ,
       659.13677443, 179.45508459, 536.9481982 , 468.48015776,
       653.4748435 , 318.41704284, 538.74811408, 658.6088479 ,
       223.37013387, 428.16362076, 528.76901842, 406.37551074,
       138.74202493, 333.44342609, 447.048811  , 454.86395379,
       475.1486802 , 466.83788941, 269.93974529, 341.81991813,
       286.8976434 , 727.10012981, 106.93569177, 272.44420478,
       339.86639239, 191.59285901, 292.74626817, 186.34811855,
       317.90559259])

In [148]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'VEGF,  пг/мл (N40-600)'] = preds[i]
    i += 1

In [149]:
sub_data = pd.DataFrame.copy(data)

In [150]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [151]:
ANG_target = data['АТ к S100b']

In [152]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [153]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [154]:
preds = model_col.predict(data_test)

In [155]:
preds

array([1645.89239905, 1554.33505855, 3359.4494243 ,  666.89497565,
        429.60095904,  272.27522274,  328.83483171,  321.01732069,
        272.79798893,  323.92050028,  478.28307772,  261.89496144,
        122.57569895,   66.27434899,  287.92809126,  168.87556884,
        287.54041038,  312.86771826,  162.81130168, 2901.47443721,
        118.76084019,  173.10073909,  224.00851284,  126.89317398,
        448.08024834,  183.6844042 ,  261.68388817,  417.78329813,
        771.37436288,  144.36897743,  413.63871746, 1449.96466069,
        139.38064558,   86.47648162,  271.11360071,  739.28279159,
        249.25421855,  325.44047517,  331.58101428,  623.81923116,
        529.37592139,  886.20995483,  215.52873432,   75.5741734 ,
        243.98010928,  332.23430527,  405.92651255,  340.88486513,
        504.91064089,  282.34271788,  223.04601171,  449.82622522,
        203.82136606,  586.99840204,  431.2612465 ,  490.23272989,
        326.38357241,  314.99312951,  310.56946529,  448.26552

In [156]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'АТ к S100b'] = preds[i]
    i += 1

In [157]:
sub_data = pd.DataFrame.copy(data)

In [158]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [159]:
ANG_target = data['АТ к Анг  II ']

In [160]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [161]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [162]:
preds = model_col.predict(data_test)

In [163]:
preds

array([1031.14214991,  926.23593892, 1226.67390287,  663.16908682,
        488.56699764,  205.79176415,  160.52140415,  356.71567368,
        439.89473741,  762.70329802,  147.20310944,  134.06953115,
        857.03235977,  201.54734792,  228.31656669,  287.71606165,
        681.66884221,  820.70122262,  568.98572897,  274.36333036,
        627.7446858 ,  204.78387192,  615.24381909,  216.82057046,
        191.99223265,  323.53328552,  851.78565486,  241.59313694,
        566.73083544,  141.19111427,  287.91122673,  849.79335043,
        563.71688897,  217.13499166,  304.43588435,  239.23752036,
        306.30529557,  260.71338316,  428.08357967,  753.52256005,
        335.82680522,  209.83760562,  287.52995093,   96.08810754,
        295.72173209,  838.40966837,  254.97101838,  377.42468383,
        272.21032924,  460.71295149,  704.66279488,  222.95113308,
        159.49644606,  609.87535446,  617.86449555,  345.25488856,
        204.54949113,  442.77666085,  243.35455023,  200.51166

In [164]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'АТ к Анг  II '] = preds[i]
    i += 1

In [165]:
sub_data = pd.DataFrame.copy(data)

In [166]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [167]:
ANG_target = data['АТ к ЭТ ']

In [168]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [169]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [170]:
preds = model_col.predict(data_test)

In [171]:
preds

array([1702.42484641,  192.4149682 ,  392.67400885,  141.65880436,
        219.7200646 ,  374.08728481,  237.05006816,  172.53741173,
        295.13509745,  129.20167611,  174.55094462,  261.84637163,
        165.04688735,  238.7436955 ,  643.6508116 ,  143.47249855,
        187.68006478,   28.37406615,   28.83948946,   75.50825596,
        213.38562877,  160.87958299,  113.27735602,  220.75855611,
         72.56202046,   28.04374464,  127.6644167 ,  293.96443641,
        320.28414362,  276.93724155,  280.5309196 ,  339.77672334,
        373.85269222,  504.88712904,  160.78718368, 1907.06397778,
        206.72236901,  279.57090179,  540.27089386,  281.4028532 ,
        146.4361948 ,  268.41445713,  282.15558209,  291.35204745,
        212.23264794,  116.75492282,  255.66348972,  119.15779492,
        581.17239416,  153.52183056,  357.53586006,  145.92641942,
        617.05140517,  189.27678967,  164.38972658,  646.76102027,
        156.72460885,  375.54838191,  490.93419525, 1541.03745

In [172]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'АТ к ЭТ '] = preds[i]
    i += 1

In [173]:
sub_data = pd.DataFrame.copy(data)

In [174]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [175]:
ANG_target = data['АТ к HLDF- 24']

In [176]:
data_test = sub_data.loc[S100b_anti_labels]
data_train = sub_data.loc[S100b_labels]
target_test = ANG_target.loc[S100b_anti_labels]
target_train = ANG_target.loc[S100b_labels]

In [177]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [178]:
preds = model_col.predict(data_test)

In [179]:
preds

array([189.77486731,  74.80336472,  55.19498646,  61.62585852,
        55.8800326 ,  91.03343492, 299.69193331,  95.2690351 ,
       101.92430806,  56.57632057, 121.55471712,  66.01253488,
       364.84249619,  95.2636147 , 104.74009185,  84.27491163,
       152.22500204,  51.75397315,  56.71081595,  48.96144195,
        70.02391862,  96.80503179,  87.77135453, 257.89613195,
        94.49099348,  85.43492747,  49.7549319 ,  76.5275978 ,
        64.24702122, 291.74802754,  80.81170459,  68.20118488,
       146.6350108 , 242.55628375,  88.15422043, 468.05246025,
        66.23248483,  97.74932995, 142.15995834, 202.47315791,
       127.35371756, 131.96847676, 164.84875021, 159.21418407,
        82.12057763,  76.56470612,  91.0301853 , 144.88594705,
       224.87542878,  84.64214301,  56.64909887,  77.77981448,
       100.97137523, 115.44925681, 195.10896674, 106.55966466,
        97.1497683 , 100.48885961,  71.4095962 , 146.98624706,
        62.52189086])

In [180]:
i = 0

for item in S100b_anti_labels:
    
    data.loc[item, 'АТ к HLDF- 24'] = preds[i]
    i += 1

In [181]:
sub_data = pd.DataFrame.copy(data)

In [182]:
sub_data.drop(columns={'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'target'}, inplace = True)
sub_data.head(5)

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
1     2.0      6.2       5.9        110           443         6.2    1.07   
2     3.0      5.2       5.0         72           164         5.5    2.27   
3     4.0      5.1       5.8         85           345         6.6    2.10   
4     5.0      5.6       5.7         74           438         6.3    1.04   
5    12.0      5.7       5.5         88           286         7.1    0.91   

   Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
1    4.25          2.37              20.00  ...       0               0   
2    3.39          0.64              20.69  ...       1               0   
3    4.14          0.36              30.47  ...       0               1   
4    3.96          3.38              31.80  ...       0               0   
5    5.33          1.80              26.50  ...       0               0   

   laborers  servants  leadership  scientific  engineering  no_job_data  \
1         1         0           0           0            0            0   
2         0         0           0           0            1            0   
3         0         0           0           0            1            0   
4         1         0           0           0            0            0   
5         1         0           0           0            0            0   

   retiree   age  
1        0  63.0  
2        0  57.0  
3        0  57.0  
4        0  55.0  
5        0  60.0  

[5 rows x 34 columns]

In [183]:
ANG_target = data['HLDF (нг/мл']

In [184]:
HLDF_labels = data[data['HLDF (нг/мл'] < 10000].index.tolist()

In [185]:
HLDF_anti_labels = []
for i in range(1, 118):
    HLDF_anti_labels.append(i)
    
for item in HLDF_labels:
    HLDF_anti_labels.remove(item)
    
HLDF_anti_labels

[1,
 2,
 3,
 4,
 17,
 18,
 19,
 22,
 24,
 27,
 28,
 29,
 30,
 34,
 35,
 37,
 38,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 49,
 51,
 52,
 55,
 56,
 59,
 60,
 64,
 65,
 66,
 67,
 68,
 70,
 73,
 74,
 76,
 78,
 81,
 82,
 86,
 87,
 88,
 89,
 90,
 93,
 94,
 97,
 98,
 100,
 101,
 102,
 103,
 104,
 107,
 109,
 110,
 111,
 112,
 114,
 115,
 116,
 117]

In [186]:
data_test = sub_data.loc[HLDF_anti_labels]
data_train = sub_data.loc[HLDF_labels]
target_test = ANG_target.loc[HLDF_anti_labels]
target_train = ANG_target.loc[HLDF_labels]

In [187]:
model_col.fit(data_train, target_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=300,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [188]:
preds = model_col.predict(data_test)

In [189]:
preds

array([101.95205035, 101.67785393, 112.60960984,  94.85603074,
        78.72415057, 105.98969795, 110.07289586,  78.71752332,
       113.46992461,  86.57936182,  67.24469841, 116.3960788 ,
        83.85244583,  49.65100548,  85.05032318,  81.35765828,
        85.86797378,  80.61555827,  72.70238655,  69.6119858 ,
        95.26570013,  63.94985247,  81.18758142,  76.09800029,
        94.04224224, 101.01722585,  79.27613687, 104.58767416,
        92.53686195,  88.87686495,  82.56009478,  68.84902023,
        77.6997678 ,  94.34275474, 104.4217223 , 102.42825465,
        83.69049573,  85.90875195, 126.61977261,  84.91798543,
        84.2695947 ,  93.89907927,  85.78126522,  81.53241795,
        68.15677923,  57.32627665,  61.49874098,  57.8336544 ,
        57.7359269 ,  72.89040623,  66.36385097,  77.87213539,
        59.34330514,  65.85285131,  63.75275126,  76.7460784 ,
        62.03107545,  82.78692898,  66.71679034, 107.77332171,
        95.43177048,  60.28209454,  78.4107406 ,  75.54

In [190]:
i = 0

for item in HLDF_anti_labels:
    
    data.loc[item, 'HLDF (нг/мл'] = preds[i]
    i += 1

In [191]:
data.fillna(0, inplace = True)

In [192]:
sub_data = pd.DataFrame.copy(data)

In [193]:
target_col = sub_data['target']

In [194]:
sub_data.drop(columns={'target'}, inplace = True)

In [195]:
data_test = sub_data.loc[Index_label]
data_train = sub_data.loc[Anti_Index_label]
target_test = target_col.loc[Index_label]
target_train = target_col.loc[Anti_Index_label]

In [196]:
target_train

61     о
62     о
63     о
64     о
65     о
66     о
67     о
68     п
69     п
70     п
71     п
72     п
73     п
74     п
75     п
76     п
77     п
78     п
79     п
80     п
81     п
82     п
83     п
84     п
85     п
86     п
87     п
88     п
89     п
90     п
91     п
92     п
93     п
94     п
95     п
96     п
97     п
98     п
99     п
100    п
101    п
102    п
103    п
104    п
105    п
106    п
107    п
108    п
109    п
110    п
111    п
112    п
113    п
114    п
115    п
116    п
117    п
Name: target, dtype: object

In [197]:
model.fit(data_train, target_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=300,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [198]:
preds_with_fill = model.predict(data_test)

In [199]:
preds_with_fill

array(['п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п',
       'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п',
       'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п',
       'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п',
       'п', 'п', 'п', 'п', 'п', 'п', 'п', 'п'], dtype=object)

...

In [200]:
target_col.replace({0 : 'о','O' : 'о'}, inplace = True)
target_col.unique()

array(['о', 'п'], dtype=object)

In [201]:
sub_data.drop(columns={'target'}, inplace = True)

In [202]:
summed_with_GBR = 0

for train_split, test_split in folds.split(sub_data, target):
    
    #print(train_split, test_split)

    data_train, data_test = sub_data.loc[train_split + 1], sub_data.loc[test_split + 1]
    targ_train, targ_test = target.loc[train_split + 1], target.loc[test_split + 1]
    
    model.fit(data_train, targ_train)
    pred = model.predict(data_test)
    
    summed_with_GBR += ac_s(targ_test, pred)
    print("Accuracy: ", ac_s(targ_test, pred))
    
summed_with_GBR /= 8

Accuracy:  0.875
Accuracy:  0.625
Accuracy:  0.6666666666666666
Accuracy:  0.8571428571428571
Accuracy:  0.8571428571428571
Accuracy:  0.8571428571428571
Accuracy:  0.9285714285714286
Accuracy:  0.5714285714285714


In [203]:
sub_data.drop(columns={'ДАД', 'САД'}, inplace = True)

In [204]:
summed_without_GBR = 0

for train_split, test_split in folds.split(sub_data, target):
    
    #print(train_split, test_split)

    data_train, data_test = sub_data.loc[train_split + 1], sub_data.loc[test_split + 1]
    targ_train, targ_test = target.loc[train_split + 1], target.loc[test_split + 1]
    
    model.fit(data_train, targ_train)
    pred = model.predict(data_test)
    
    summed_without_GBR += ac_s(targ_test, pred)
    print("Accuracy: ", ac_s(targ_test, pred))
    
summed_without_GBR /= 8

Accuracy:  0.75
Accuracy:  0.8125
Accuracy:  0.6666666666666666
Accuracy:  0.6428571428571429
Accuracy:  0.5
Accuracy:  0.7142857142857143
Accuracy:  0.7857142857142857
Accuracy:  0.7142857142857143


In [205]:
summed_with, summed_without, summed_with_GBR, summed_without_GBR

(0.8288690476190476,
 0.7551339285714286,
 0.7797619047619048,
 0.6982886904761905)