In [106]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

def check_metrics(true_val, pred_val):
    print("Accuracy: ", accuracy_score(true_val, pred_val))
    print("Roc_Auc: ", roc_auc_score(true_val, pred_val))
    print("Precision: ", precision_score(true_val, pred_val), " - процент правильно определенных положительных")
    print("Recall: ", recall_score(true_val, pred_val), " - процент выбранных положительных")


In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("~/Desktop/data.xls",header = 3)

In [3]:
data.head(5)

Unnamed: 0        Unnamed: 1  Unnamed: 2  Unnamed: 3 Глюкоза Мочевина  \
0         NaN               NaN         NaN         NaN    мМ/Л     мМ/Л   
1         2.0      Сл-сантехник         2.0      1956.0     6.2      5.9   
2         3.0          инженер          1.0      1962.0     5.2        5   
3         4.0  Инженер-технолог     -1000.0      1962.0     5.1      5.8   
4         5.0          водитель         2.0      1964.0     5.6      5.7   

  Креатинин Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
0     мкМ/Л        мкМ/Л       мМ/Л   мМ/Л  ...                           NaN   
1       110          443        6.2   1.07  ...                           NaN   
2        72          164        5.5   2.27  ...                           NaN   
3        85          345        6.6    2.1  ...                           NaN   
4        74          438        6.3   1.04  ...                          0.38   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
0                      NaN                    NaN         NaN        NaN   
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                  458.4         NaN     1600.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
0           NaN      NaN           NaN         NaN         NaN  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  

[5 rows x 37 columns]

In [4]:
data = data.drop(0)

In [5]:
data = data.rename(columns={"Unnamed: 0" : "Number", "Unnamed: 1" : "Profession"})
data = data.rename(columns={"Unnamed: 2" : "Gender", "Unnamed: 3" : "Birth_year"})

In [6]:
data.head(5)

Number        Profession  Gender  Birth_year Глюкоза Мочевина Креатинин  \
1     2.0      Сл-сантехник     2.0      1956.0     6.2      5.9       110   
2     3.0          инженер      1.0      1962.0     5.2        5        72   
3     4.0  Инженер-технолог -1000.0      1962.0     5.1      5.8        85   
4     5.0          водитель     2.0      1964.0     5.6      5.7        74   
5    12.0          слесарь      2.0      1959.0     5.7      5.5        88   

  Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
1          443        6.2   1.07  ...                           NaN   
2          164        5.5   2.27  ...                           NaN   
3          345        6.6    2.1  ...                           NaN   
4          438        6.3   1.04  ...                          0.38   
5          286        7.1   0.91  ...                          0.00   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                 458.40         NaN     1600.0   
5                     0.32                  70.91       120.0      400.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  
5         400.0    600.0         100.0           0        12.0  

[5 rows x 37 columns]

In [7]:
data.columns

Index(['Number', 'Profession', 'Gender', 'Birth_year', 'Глюкоза', 'Мочевина',
       'Креатинин', 'Мочевая к-та', 'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП',
       'Триглицериды', 'индекс массы тела', 'курк\ение',
       'избыт, Потр, Алкоголя', 'и,п повар, Соли', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб', 'САД', 'ДАД',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='object')

In [8]:
data['Profession'].unique().__len__()
# дропнуть штоле?

56

In [9]:
data = data.drop(columns={"Unnamed: 36"})

In [10]:
data = data.rename(columns={"Unnamed: 35" : "Target"})

In [11]:
data["Target"].unique()

array([0, 'о', 'п'], dtype=object)

In [12]:
data["Target"].replace({0 : 'о'}, inplace = True)

In [13]:
data["male"] = (data["Gender"] == 2).astype(int)
data["female"] = (data["Gender"] == 1).astype(int)
data["no_spec_gender"] = (data["Gender"] == -1000).astype(int)
data = data.drop(columns={"Gender"})

In [14]:
data["Profession"].replace({"инженер " : "инженер", "инженр" : "инженер", "мастер " : "мастер"}, inplace=True)
data["Profession"].fillna("no_info", inplace=True)

In [15]:
#laborers - ручная работа
#servants - обсл. состав
#leadership - управление
#scientific - научные специальности, работа мозгом
#engineering - инж. специальности
#no_data - без инфы
#retiree - пенсионер
data['laborers'] = data['Profession'] == 'Сл-сантехник' 
data['laborers'] |=                    data['Profession'] == 'водитель' 
data['laborers'] |=                    data['Profession'] == 'слесарь ' 
data['laborers'] |=                    data['Profession'] == 'изолировщица' 
data['laborers'] |=                    data['Profession'] == 'аппаратчик' 
data['laborers'] |=                    data['Profession'] == 'тракторист' 
data['laborers'] |=                    data['Profession'] == 'плавильщик' 
data['laborers'] |=                    data['Profession'] == 'токарь ' 
data['laborers'] |=                    data['Profession'] == 'оператор                    1962' 
data['laborers'] |=                    data['Profession'] == 'пригот-ль р-ров' 
data['laborers'] |=                    data['Profession'] == 'монтажник РЭА' 
data['laborers'] |=                    data['Profession'] == 'техник' 
data['laborers'] |=                    data['Profession'] == 'сборщик м-схем'  
data['laborers'] |=                    data['Profession'] == 'машинист' 
data['laborers'] |=                    data['Profession'] == 'старший мастер' 
data['laborers'] |=                    data['Profession'] == 'гальваник' 
data['laborers'] |=                    data['Profession'] == 'мастер отд работ1969' 
data['laborers'] |=                    data['Profession'] == 'эл. сварщик' 
data['laborers'] |=                    data['Profession'] == 'фрезеровщик' 
data['laborers'] |=                    data['Profession'] == 'изолировщик ' 
data['laborers'] |=                    data['Profession'] == 'эл,сварщик' 
data['laborers'] |=                    data['Profession'] == 'электромонтажник' 
data['laborers'] |=                    data['Profession'] == 'маляр' 
data['laborers'] |=                    data['Profession'] == 'маляр-штукатур' 
data['laborers'] |=                    data['Profession'] == 'мастер' 
data['laborers'] |=                    data['Profession'] == 'прессовщик'
data['laborers'] |=                    data['Profession'] == 'электрик'

data['servants'] = data['Profession'] == 'горничная' 
data['servants'] |=                    data['Profession'] == 'контролер КПП' 
data['servants'] |=                    data['Profession'] == 'диспетчер' 
data['servants'] |=                    data['Profession'] == 'дежурная' 
data['servants'] |=                    data['Profession'] == 'секретарь '

data['leadership'] = data['Profession'] == 'нач группы ' 
data['leadership'] |=                     data['Profession'] == 'нач сектора' 
data['leadership'] |=                       data['Profession'] == 'гл инженер ' 
data['leadership'] |=                      data['Profession'] == 'нач-к ПРБ' 
data['leadership'] |=                      data['Profession'] == 'нач-к тех,бюро' 
data['leadership'] |=                      data['Profession'] == 'нач-к группы' 
data['leadership'] |=                      data['Profession'] == 'старший мастер' 
data['leadership'] |=                      data['Profession'] == 'нач-к бюро ' 
data['leadership'] |=                      data['Profession'] == 'нач-к сектора' 
data['leadership'] |=                      data['Profession'] == 'мастер'
data['leadership'] |=                     data['Profession'] == 'зам, нач-ка отд,'

data['scientific'] = data['Profession'] == 'внс' 
data['scientific'] |=                      data['Profession'] == 'вед,специалист'
data['scientific'] |=                      data['Profession'] == 'науч. сотр'
data['scientific'] |=                      data['Profession'] == 'нач-к тех,бюро'
data['scientific'] |=                      data['Profession'] == 'нач-к бюро '
data['scientific'] |=                      data['Profession'] == 'экономист '

data['engineering'] = data['Profession'] == 'инженер'
data['engineering'] |= data['Profession'] == 'Инженер-технолог' 
data['engineering'] |= data['Profession'] == 'гл инженер '
data['engineering'] |= data['Profession'] == 'наладчик' 
data['engineering'] |= data['Profession'] == 'измеритель' 
data['engineering'] |= data['Profession'] == 'инженер-прогр,'
data['engineering'] |= data['Profession'] == 'нач-к тех,бюро'

data['no_job_data'] = data['Profession'] == 'no_info'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕНА'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕН'

data['retiree'] = data['Profession'] == 'ПЕНСИОНЕР'

In [16]:
data['laborers'] = data['laborers'].astype(int)
data['servants'] = data['servants'].astype(int)
data['leadership'] = data['leadership'].astype(int)
data['scientific'] = data['scientific'].astype(int)
data['engineering'] = data['engineering'].astype(int)
data['no_job_data'] = data['no_job_data'].astype(int)
data['retiree'] = data['retiree'].astype(int)

In [17]:
data = data.drop(columns={'Profession'})

In [18]:
data["age"] = 2019 - data["Birth_year"]
data = data.drop(columns = {'Birth_year'})
data.head(1)

Number Глюкоза Мочевина Креатинин Мочевая к-та Холестерин Х-ЛПВП Х-ЛПНП  \
1     2.0     6.2      5.9       110          443        6.2   1.07   4.25   

  Триглицериды индекс массы тела  ... female no_spec_gender laborers servants  \
1         2.37                20  ...      0              0        1        0   

  leadership scientific engineering no_job_data retiree   age  
1          0          0           0           0       0  63.0  

[1 rows x 44 columns]

In [19]:
data['ГЛЖ ин Соколова-Лайона'].replace({"нет" : np.NaN, "да" : np.NaN}, inplace = True)

In [20]:
data.replace({"нет" : 0, "да" : 1, "нет " : 0, "да " : 1, "не" : 0}, inplace = True)

In [21]:
data.rename(columns={'курк\ение' : 'smoking', 'избыт, Потр, Алкоголя' : 'Alcoholic'}, inplace=True)

In [22]:
data['smoking'].replace({'нет нет' : 0}, inplace = True)
data['smoking'].unique(), data['smoking'].dtype

(array([1, 0]), dtype('int64'))

In [23]:
data['Alcoholic'].replace({'нет нет нет нет нет ' : 0, "нет  нет нет" : 0}, inplace = True)
data['Alcoholic'].unique(), data['Alcoholic'].dtype

(array([0, 1]), dtype('int64'))

In [24]:
data.rename(columns={'и,п повар, Соли' : 'excess_salt_consumption'}, inplace = True)
data['excess_salt_consumption'].unique()

array([0, 1])

In [25]:
data['гиподинамия'].replace({'нетт' : 0}, inplace = True)
data["гиподинамия"].unique(), data['гиподинамия'].dtype

(array([0, 1]), dtype('int64'))

In [26]:
data.replace({'уволил' : 6.0}, inplace = True)

In [27]:
data['индекс массы тела'].unique()

array([20, 20.69, 30.47, 31.8, 26.5, 40.2, 23.9, 41.03, 32.5, 21.5, 30.07,
       24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44, 19.89, 22.86,
       31.56, 25.5, 27.89, 29.4, 17.65, 29.05, 23.08, 45.3, 38.37, 23.12,
       25.46, 29.04, 24.68, 28.93, 27.14, 23.67, 29.31, 29.17, 27.44,
       26.22, 23.31, 27.66, 25.28, 23.44, '21, 08', 21.88, '26, 47', 24.8,
       18.78, 34.05, 20.28, 32, 48.33, 32.27, 21.64, 28.4, 27.87, 24.1,
       29.58, 33.08, 43.7, 28.08, 26.47, 22.84, 25.53, 23.14, 23.23, 22.3,
       40.16, 35.8, 26.85, 33.02, 23.05, 28.03, 28.41, 27.04, 38.74,
       28.34, 29.68, 24.6, 29.76, 27.68, 27.97, 27.12, 33.21, 39.92,
       25.16, 33.39, 31.23, '25, 04', 34.21, 49.08, 23.66, 24.16, 23.42,
       32.18, 25.84, 32.6, 26.9, 24.22, 22.34, 24.45, 27.24, 31.14, 22.03,
       36.06, 22.92, 24.54, 23.72, 29.07, 33.75, 19.14, 30.86, 27.09,
       25.03], dtype=object)

In [28]:
help_array = np.empty(len(data))

In [30]:
for enum, item in enumerate(data['индекс массы тела']):
    if type(item) == str:
        sub_str = item[0:2] + "." + item[4:]
        sub_float = float(sub_str)
        print(sub_float, type(sub_float))
        help_array[enum] = sub_float
        
    else:
        help_array[enum] = item

21.08 <class 'float'>
26.47 <class 'float'>
25.04 <class 'float'>


In [31]:
data['индекс массы тела'] = help_array

In [32]:
data['индекс массы тела'].unique()

array([20.  , 20.69, 30.47, 31.8 , 26.5 , 40.2 , 23.9 , 41.03, 32.5 ,
       21.5 , 30.07, 24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44,
       19.89, 22.86, 31.56, 25.5 , 27.89, 29.4 , 17.65, 29.05, 23.08,
       45.3 , 38.37, 23.12, 25.46, 29.04, 24.68, 28.93, 27.14, 23.67,
       29.31, 29.17, 27.44, 26.22, 23.31, 27.66, 25.28, 23.44, 21.08,
       21.88, 26.47, 24.8 , 18.78, 34.05, 20.28, 32.  , 48.33, 32.27,
       21.64, 28.4 , 27.87, 24.1 , 29.58, 33.08, 43.7 , 28.08, 22.84,
       25.53, 23.14, 23.23, 22.3 , 40.16, 35.8 , 26.85, 33.02, 23.05,
       28.03, 28.41, 27.04, 38.74, 28.34, 29.68, 24.6 , 29.76, 27.68,
       27.97, 27.12, 33.21, 39.92, 25.16, 33.39, 31.23, 25.04, 34.21,
       49.08, 23.66, 24.16, 23.42, 32.18, 25.84, 32.6 , 26.9 , 24.22,
       22.34, 24.45, 27.24, 31.14, 22.03, 36.06, 22.92, 24.54, 23.72,
       29.07, 33.75, 19.14, 30.86, 27.09, 25.03])

In [33]:
data.dtypes

Number                           float64
Глюкоза                          float64
Мочевина                         float64
Креатинин                          int64
Мочевая к-та                       int64
Холестерин                       float64
Х-ЛПВП                           float64
Х-ЛПНП                           float64
Триглицериды                     float64
индекс массы тела                float64
smoking                            int64
Alcoholic                          int64
excess_salt_consumption            int64
гиподинамия                        int64
стресс                             int64
прием п\щ контрац                  int64
насл отяг, По ГБ,                  int64
насл отяг, По ССЗ                  int64
насл отяг, По СД                   int64
насл, Отяг по почечн, Заб          int64
САД                              float64
ДАД                              float64
ГЛЖ ин Соколова-Лайона           float64
S100b, нг/л (N до 90)             object
Анг II, пг/мл (N

In [34]:
data['S100b, нг/л (N до 90)'].replace({'ИНФАРКТ МОЗГА В 2018 ГОДУ' : -1}, inplace = True)

In [35]:
from sklearn.model_selection import train_test_split

In [413]:
train_data, test_data, train_target, test_target = train_test_split(data.drop(columns = {"Target"}), np.array(data["Target"]),
                                                                    test_size = 0.3, random_state=17)

In [414]:
test_target[np.where(test_target == 'п')] = 1

In [415]:
test_target[np.where(test_target == 'о')] = -1

In [416]:
train_target[np.where(train_target == 'п')] = 1

In [417]:
train_target[np.where(train_target == 'о')] = -1

In [418]:
test_target = test_target.astype(int)
train_target = train_target.astype(int)

In [419]:
from sklearn.tree import DecisionTreeClassifier

In [430]:
DTC = DecisionTreeClassifier(criterion="entropy")

In [433]:
classifier = AdaBoostClassifier(base_estimator=DTC)

In [435]:
classifier.fit(train_data.fillna(0), train_target)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='entropy',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                       

In [436]:
check_metrics(test_target, classifier.predict(test_data.fillna(0)))

Accuracy:  0.8055555555555556
Roc_Auc:  0.8
Precision:  0.8  - процент правильно определенных положительных
Recall:  0.75  - процент выбранных положительных


In [441]:
DTC.fit(train_data.fillna(0), train_target)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [442]:
check_metrics(test_target, DTC.predict(test_data.fillna(0)))

Accuracy:  0.8888888888888888
Roc_Auc:  0.8875
Precision:  0.875  - процент правильно определенных положительных
Recall:  0.875  - процент выбранных положительных


In [423]:
RFC = RandomForestClassifier(n_estimators = 200, criterion='entropy')

In [424]:
RFC.fit(train_data.fillna(0), train_target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [425]:
check_metrics(test_target, RFC.predict(test_data.fillna(0)))

Accuracy:  0.7777777777777778
Roc_Auc:  0.7625000000000001
Precision:  0.8333333333333334  - процент правильно определенных положительных
Recall:  0.625  - процент выбранных положительных


In [426]:
from sklearn.ensemble import AdaBoostClassifier

In [427]:
classifier = AdaBoostClassifier()

In [428]:
classifier.fit(train_data.fillna(0), train_target)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [429]:
check_metrics(test_target, classifier.predict(test_data.fillna(0)))

Accuracy:  0.8055555555555556
Roc_Auc:  0.7937500000000001
Precision:  0.8461538461538461  - процент правильно определенных положительных
Recall:  0.6875  - процент выбранных положительных


In [75]:
from sklearn.svm import SVC

In [404]:
svc = SVC(probability=False, kernel='linear')
abc = AdaBoostClassifier(base_estimator=svc)

In [409]:
svc = SVC(probability=True, kernel='linear')

In [410]:
svc.fit(train_data.fillna(0), train_target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [411]:
check_metrics(test_target, svc.predict(test_data.fillna(0)))

Accuracy:  0.5833333333333334
Roc_Auc:  0.5811688311688311
Precision:  0.47058823529411764  - процент правильно определенных положительных
Recall:  0.5714285714285714  - процент выбранных положительных


In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
RFC = RandomForestClassifier()

In [104]:
RFC.fit(train_data.fillna(0), train_target)

/usr/local/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [107]:
check_metrics(test_target, RFC.predict(test_data.fillna(0)))

Accuracy:  0.8333333333333334
Roc_Auc:  0.8142857142857143
Precision:  0.875  - процент правильно определенных положительных
Recall:  0.7  - процент выбранных положительных


In [129]:
train_array = np.array(train_data)

In [139]:
train_array = np.c_[train_array[:, :23], train_array[:, 32:]]

In [140]:
train_array[0]

array([ 35.  ,   5.8 ,   5.3 , 109.  , 462.  ,   5.8 ,   1.56,   3.74,
         1.52,  23.05,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  , 110.  ,  70.  ,  20.  ,   1.  ,
         0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,  42.  ])

In [141]:
test_array = np.array(test_data)

In [142]:
test_array = np.c_[test_array[:, :23], test_array[:, 32:]]

In [149]:
classifier.fit(np.nan_to_num(train_array), train_target)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [150]:
check_metrics(test_target, classifier.predict(np.nan_to_num(test_array)))

Accuracy:  0.75
Roc_Auc:  0.7285714285714286
Precision:  0.75  - процент правильно определенных положительных
Recall:  0.6  - процент выбранных положительных


In [165]:
train_array = np.array(train_data)
test_array = np.array(test_data)

In [166]:
train_array = train_array[:, 23:32]
test_array = test_array[:, 23:32]

In [158]:
classifier.fit(np.nan_to_num(train_array), train_target)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [159]:
check_metrics(test_target, classifier.predict(np.nan_to_num(test_array)))

Accuracy:  0.625
Roc_Auc:  0.6785714285714286
Precision:  0.5263157894736842  - процент правильно определенных положительных
Recall:  1.0  - процент выбранных положительных


In [161]:
np.nanmean(train_array, axis=0)

array([ 63.81888889, 218.365     ,   0.65909091, 321.65272727,
        89.73170732, 465.90909091, 343.18181818, 246.59090909,
        95.45454545])

In [167]:
inds = np.where(np.isnan(train_array))
train_array[inds] = np.take(np.nanmean(train_array, axis=0), inds[1])

In [168]:
inds = np.where(np.isnan(test_array))
test_array[inds] = np.take(np.nanmean(test_array, axis=0), inds[1])

In [169]:
classifier.fit(train_array, train_target)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [170]:
check_metrics(test_target, classifier.predict(test_array))

Accuracy:  0.625
Roc_Auc:  0.6642857142857143
Precision:  0.5294117647058824  - процент правильно определенных положительных
Recall:  0.9  - процент выбранных положительных
