In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("~/Desktop/data.xls",header = 3)

In [3]:
data.head(5)

Unnamed: 0        Unnamed: 1  Unnamed: 2  Unnamed: 3 Глюкоза Мочевина  \
0         NaN               NaN         NaN         NaN    мМ/Л     мМ/Л   
1         2.0      Сл-сантехник         2.0      1956.0     6.2      5.9   
2         3.0          инженер          1.0      1962.0     5.2        5   
3         4.0  Инженер-технолог     -1000.0      1962.0     5.1      5.8   
4         5.0          водитель         2.0      1964.0     5.6      5.7   

  Креатинин Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
0     мкМ/Л        мкМ/Л       мМ/Л   мМ/Л  ...                           NaN   
1       110          443        6.2   1.07  ...                           NaN   
2        72          164        5.5   2.27  ...                           NaN   
3        85          345        6.6    2.1  ...                           NaN   
4        74          438        6.3   1.04  ...                          0.38   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
0                      NaN                    NaN         NaN        NaN   
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                  458.4         NaN     1600.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
0           NaN      NaN           NaN         NaN         NaN  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  

[5 rows x 37 columns]

In [4]:
data = data.drop(0)

In [5]:
data = data.rename(columns={"Unnamed: 0" : "Number", "Unnamed: 1" : "Profession"})
data = data.rename(columns={"Unnamed: 2" : "Gender", "Unnamed: 3" : "Birth_year"})

In [6]:
data.head(5)

Number        Profession  Gender  Birth_year Глюкоза Мочевина Креатинин  \
1     2.0      Сл-сантехник     2.0      1956.0     6.2      5.9       110   
2     3.0          инженер      1.0      1962.0     5.2        5        72   
3     4.0  Инженер-технолог -1000.0      1962.0     5.1      5.8        85   
4     5.0          водитель     2.0      1964.0     5.6      5.7        74   
5    12.0          слесарь      2.0      1959.0     5.7      5.5        88   

  Мочевая к-та Холестерин Х-ЛПВП  ... Анг II, пг/мл (N 10-60 пг/мл)  \
1          443        6.2   1.07  ...                           NaN   
2          164        5.5   2.27  ...                           NaN   
3          345        6.6    2.1  ...                           NaN   
4          438        6.3   1.04  ...                          0.38   
5          286        7.1   0.91  ...                          0.00   

  ЭТ, пмоль/л    (N =0,09) VEGF,  пг/мл (N40-600) HLDF (нг/мл АТ к S100b  \
1                      NaN                    NaN         NaN        NaN   
2                      NaN                    NaN         NaN        NaN   
3                      NaN                    NaN         NaN        NaN   
4                     0.07                 458.40         NaN     1600.0   
5                     0.32                  70.91       120.0      400.0   

  АТ к Анг  II  АТ к ЭТ  АТ к HLDF- 24 Unnamed: 35 Unnamed: 36  
1           NaN      NaN           NaN           0         2.0  
2           NaN      NaN           NaN           0         3.0  
3           NaN      NaN           NaN           0         4.0  
4        1600.0    400.0          50.0           0         5.0  
5         400.0    600.0         100.0           0        12.0  

[5 rows x 37 columns]

In [7]:
data.columns

Index(['Number', 'Profession', 'Gender', 'Birth_year', 'Глюкоза', 'Мочевина',
       'Креатинин', 'Мочевая к-та', 'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП',
       'Триглицериды', 'индекс массы тела', 'курк\ение',
       'избыт, Потр, Алкоголя', 'и,п повар, Соли', 'гиподинамия', 'стресс',
       'прием п\щ контрац', 'насл отяг, По ГБ, ', 'насл отяг, По ССЗ',
       'насл отяг, По СД', 'насл, Отяг по почечн, Заб', 'САД', 'ДАД',
       'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='object')

In [8]:
data['Profession'].unique().__len__()
# дропнуть штоле?

56

In [9]:
data = data.drop(columns={"Unnamed: 36"})

In [10]:
data = data.rename(columns={"Unnamed: 35" : "Target"})

In [11]:
data["Target"].unique()

array([0, 'о', 'п'], dtype=object)

In [12]:
data["Target"].replace({0 : 'о'}, inplace = True)

In [13]:
data["male"] = (data["Gender"] == 2).astype(int)
data["female"] = (data["Gender"] == 1).astype(int)
data["no_spec_gender"] = (data["Gender"] == -1000).astype(int)
data = data.drop(columns={"Gender"})

In [14]:
data["Profession"].replace({"инженер " : "инженер", "инженр" : "инженер", "мастер " : "мастер"}, inplace=True)
data["Profession"].fillna("no_info", inplace=True)

In [15]:
#laborers - ручная работа
#servants - обсл. состав
#leadership - управление
#scientific - научные специальности, работа мозгом
#engineering - инж. специальности
#no_data - без инфы
#retiree - пенсионер
data['laborers'] = data['Profession'] == 'Сл-сантехник' 
data['laborers'] |=                    data['Profession'] == 'водитель' 
data['laborers'] |=                    data['Profession'] == 'слесарь ' 
data['laborers'] |=                    data['Profession'] == 'изолировщица' 
data['laborers'] |=                    data['Profession'] == 'аппаратчик' 
data['laborers'] |=                    data['Profession'] == 'тракторист' 
data['laborers'] |=                    data['Profession'] == 'плавильщик' 
data['laborers'] |=                    data['Profession'] == 'токарь ' 
data['laborers'] |=                    data['Profession'] == 'оператор                    1962' 
data['laborers'] |=                    data['Profession'] == 'пригот-ль р-ров' 
data['laborers'] |=                    data['Profession'] == 'монтажник РЭА' 
data['laborers'] |=                    data['Profession'] == 'техник' 
data['laborers'] |=                    data['Profession'] == 'сборщик м-схем'  
data['laborers'] |=                    data['Profession'] == 'машинист' 
data['laborers'] |=                    data['Profession'] == 'старший мастер' 
data['laborers'] |=                    data['Profession'] == 'гальваник' 
data['laborers'] |=                    data['Profession'] == 'мастер отд работ1969' 
data['laborers'] |=                    data['Profession'] == 'эл. сварщик' 
data['laborers'] |=                    data['Profession'] == 'фрезеровщик' 
data['laborers'] |=                    data['Profession'] == 'изолировщик ' 
data['laborers'] |=                    data['Profession'] == 'эл,сварщик' 
data['laborers'] |=                    data['Profession'] == 'электромонтажник' 
data['laborers'] |=                    data['Profession'] == 'маляр' 
data['laborers'] |=                    data['Profession'] == 'маляр-штукатур' 
data['laborers'] |=                    data['Profession'] == 'мастер' 
data['laborers'] |=                    data['Profession'] == 'прессовщик'
data['laborers'] |=                    data['Profession'] == 'электрик'

data['servants'] = data['Profession'] == 'горничная' 
data['servants'] |=                    data['Profession'] == 'контролер КПП' 
data['servants'] |=                    data['Profession'] == 'диспетчер' 
data['servants'] |=                    data['Profession'] == 'дежурная' 
data['servants'] |=                    data['Profession'] == 'секретарь '

data['leadership'] = data['Profession'] == 'нач группы ' 
data['leadership'] |=                     data['Profession'] == 'нач сектора' 
data['leadership'] |=                       data['Profession'] == 'гл инженер ' 
data['leadership'] |=                      data['Profession'] == 'нач-к ПРБ' 
data['leadership'] |=                      data['Profession'] == 'нач-к тех,бюро' 
data['leadership'] |=                      data['Profession'] == 'нач-к группы' 
data['leadership'] |=                      data['Profession'] == 'старший мастер' 
data['leadership'] |=                      data['Profession'] == 'нач-к бюро ' 
data['leadership'] |=                      data['Profession'] == 'нач-к сектора' 
data['leadership'] |=                      data['Profession'] == 'мастер'
data['leadership'] |=                     data['Profession'] == 'зам, нач-ка отд,'

data['scientific'] = data['Profession'] == 'внс' 
data['scientific'] |=                      data['Profession'] == 'вед,специалист'
data['scientific'] |=                      data['Profession'] == 'науч. сотр'
data['scientific'] |=                      data['Profession'] == 'нач-к тех,бюро'
data['scientific'] |=                      data['Profession'] == 'нач-к бюро '
data['scientific'] |=                      data['Profession'] == 'экономист '

data['engineering'] = data['Profession'] == 'инженер'
data['engineering'] |= data['Profession'] == 'Инженер-технолог' 
data['engineering'] |= data['Profession'] == 'гл инженер '
data['engineering'] |= data['Profession'] == 'наладчик' 
data['engineering'] |= data['Profession'] == 'измеритель' 
data['engineering'] |= data['Profession'] == 'инженер-прогр,'
data['engineering'] |= data['Profession'] == 'нач-к тех,бюро'

data['no_job_data'] = data['Profession'] == 'no_info'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕНА'
data['no_job_data'] |= data['Profession'] == 'УВОЛЕН'

data['retiree'] = data['Profession'] == 'ПЕНСИОНЕР'

In [16]:
data['laborers'] = data['laborers'].astype(int)
data['servants'] = data['servants'].astype(int)
data['leadership'] = data['leadership'].astype(int)
data['scientific'] = data['scientific'].astype(int)
data['engineering'] = data['engineering'].astype(int)
data['no_job_data'] = data['no_job_data'].astype(int)
data['retiree'] = data['retiree'].astype(int)

In [17]:
data = data.drop(columns={'Profession'})

In [18]:
data["age"] = 2019 - data["Birth_year"]
data = data.drop(columns = {'Birth_year'})
data.head(1)

Number Глюкоза Мочевина Креатинин Мочевая к-та Холестерин Х-ЛПВП Х-ЛПНП  \
1     2.0     6.2      5.9       110          443        6.2   1.07   4.25   

  Триглицериды индекс массы тела  ... female no_spec_gender laborers servants  \
1         2.37                20  ...      0              0        1        0   

  leadership scientific engineering no_job_data retiree   age  
1          0          0           0           0       0  63.0  

[1 rows x 44 columns]

In [19]:
data['ГЛЖ ин Соколова-Лайона'].replace({"нет" : np.NaN, "да" : np.NaN}, inplace = True)

In [20]:
data.replace({"нет" : 0, "да" : 1, "нет " : 0, "да " : 1, "не" : 0}, inplace = True)

In [21]:
data.rename(columns={'курк\ение' : 'smoking', 'избыт, Потр, Алкоголя' : 'Alcoholic'}, inplace=True)

In [22]:
data['smoking'].replace({'нет нет' : 0}, inplace = True)
data['smoking'].unique(), data['smoking'].dtype

(array([1, 0]), dtype('int64'))

In [23]:
data['Alcoholic'].replace({'нет нет нет нет нет ' : 0, "нет  нет нет" : 0}, inplace = True)
data['Alcoholic'].unique(), data['Alcoholic'].dtype

(array([0, 1]), dtype('int64'))

In [24]:
data.rename(columns={'и,п повар, Соли' : 'excess_salt_consumption'}, inplace = True)
data['excess_salt_consumption'].unique()

array([0, 1])

In [25]:
data['гиподинамия'].replace({'нетт' : 0}, inplace = True)
data["гиподинамия"].unique(), data['гиподинамия'].dtype

(array([0, 1]), dtype('int64'))

In [26]:
data.replace({'уволил' : 6.0}, inplace = True)

In [27]:
data['индекс массы тела'].unique()

array([20, 20.69, 30.47, 31.8, 26.5, 40.2, 23.9, 41.03, 32.5, 21.5, 30.07,
       24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44, 19.89, 22.86,
       31.56, 25.5, 27.89, 29.4, 17.65, 29.05, 23.08, 45.3, 38.37, 23.12,
       25.46, 29.04, 24.68, 28.93, 27.14, 23.67, 29.31, 29.17, 27.44,
       26.22, 23.31, 27.66, 25.28, 23.44, '21, 08', 21.88, '26, 47', 24.8,
       18.78, 34.05, 20.28, 32, 48.33, 32.27, 21.64, 28.4, 27.87, 24.1,
       29.58, 33.08, 43.7, 28.08, 26.47, 22.84, 25.53, 23.14, 23.23, 22.3,
       40.16, 35.8, 26.85, 33.02, 23.05, 28.03, 28.41, 27.04, 38.74,
       28.34, 29.68, 24.6, 29.76, 27.68, 27.97, 27.12, 33.21, 39.92,
       25.16, 33.39, 31.23, '25, 04', 34.21, 49.08, 23.66, 24.16, 23.42,
       32.18, 25.84, 32.6, 26.9, 24.22, 22.34, 24.45, 27.24, 31.14, 22.03,
       36.06, 22.92, 24.54, 23.72, 29.07, 33.75, 19.14, 30.86, 27.09,
       25.03], dtype=object)

In [28]:
help_array = np.empty(len(data))

In [29]:
for enum, item in enumerate(data['индекс массы тела']):
    if type(item) == str:
        sub_str = item[0:2] + "." + item[4:]
        sub_float = float(sub_str)
        print(sub_float, type(sub_float))
        help_array[enum] = sub_float
        
    else:
        help_array[enum] = item

21.08 <class 'float'>
26.47 <class 'float'>
25.04 <class 'float'>


In [30]:
data['индекс массы тела'] = help_array

In [31]:
data['индекс массы тела'].unique()

array([20.  , 20.69, 30.47, 31.8 , 26.5 , 40.2 , 23.9 , 41.03, 32.5 ,
       21.5 , 30.07, 24.15, 29.32, 26.64, 25.47, 31.05, 21.01, 18.44,
       19.89, 22.86, 31.56, 25.5 , 27.89, 29.4 , 17.65, 29.05, 23.08,
       45.3 , 38.37, 23.12, 25.46, 29.04, 24.68, 28.93, 27.14, 23.67,
       29.31, 29.17, 27.44, 26.22, 23.31, 27.66, 25.28, 23.44, 21.08,
       21.88, 26.47, 24.8 , 18.78, 34.05, 20.28, 32.  , 48.33, 32.27,
       21.64, 28.4 , 27.87, 24.1 , 29.58, 33.08, 43.7 , 28.08, 22.84,
       25.53, 23.14, 23.23, 22.3 , 40.16, 35.8 , 26.85, 33.02, 23.05,
       28.03, 28.41, 27.04, 38.74, 28.34, 29.68, 24.6 , 29.76, 27.68,
       27.97, 27.12, 33.21, 39.92, 25.16, 33.39, 31.23, 25.04, 34.21,
       49.08, 23.66, 24.16, 23.42, 32.18, 25.84, 32.6 , 26.9 , 24.22,
       22.34, 24.45, 27.24, 31.14, 22.03, 36.06, 22.92, 24.54, 23.72,
       29.07, 33.75, 19.14, 30.86, 27.09, 25.03])

In [32]:
data.dtypes

Number                           float64
Глюкоза                          float64
Мочевина                         float64
Креатинин                          int64
Мочевая к-та                       int64
Холестерин                       float64
Х-ЛПВП                           float64
Х-ЛПНП                           float64
Триглицериды                     float64
индекс массы тела                float64
smoking                            int64
Alcoholic                          int64
excess_salt_consumption            int64
гиподинамия                        int64
стресс                             int64
прием п\щ контрац                  int64
насл отяг, По ГБ,                  int64
насл отяг, По ССЗ                  int64
насл отяг, По СД                   int64
насл, Отяг по почечн, Заб          int64
САД                              float64
ДАД                              float64
ГЛЖ ин Соколова-Лайона           float64
S100b, нг/л (N до 90)             object
Анг II, пг/мл (N

In [33]:
data['S100b, нг/л (N до 90)'].replace({'ИНФАРКТ МОЗГА В 2018 ГОДУ' : -1}, inplace = True)

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
train_data, test_data, train_target, test_target = train_test_split(data.drop(columns = {"Target"}), np.array(data["Target"]),
                                                                    test_size = 0.2, random_state = 241)

In [36]:
requied_cols = train_data.columns[train_data.isnull().any()]

In [37]:
train_data["Target"] = train_target

In [38]:
ppp = train_data.groupby("Target", as_index = False)[requied_cols].mean()
ppp

Target  ГЛЖ ин Соколова-Лайона  S100b, нг/л (N до 90)  \
0      о               26.312500              65.876000   
1      п               26.552632              59.704667   

   Анг II, пг/мл (N 10-60 пг/мл)  ЭТ, пмоль/л    (N =0,09)  \
0                     319.126207                  0.641724   
1                      23.560000                  0.692667   

   VEGF,  пг/мл (N40-600)  HLDF (нг/мл  АТ к S100b  АТ к Анг  II     АТ к ЭТ   \
0              258.035172   108.230769  405.172414     331.034483  225.862069   
1              444.646667    57.666667  583.333333     366.666667  286.666667   

   АТ к HLDF- 24  
0      91.379310  
1     103.333333

In [39]:
indixes = train_data.index
indixes

Int64Index([ 73,   5,  46, 114,  79,  86,  99,  37,  27,  80,  59,  60,  94,
             68,  15,  81, 110, 105,  18,  93,   7,  34,  19,  35,  50,  16,
             92,  48,  58,  11,  20,  61,  78,  96,  76,  54, 107,  40,  33,
             87,  64,  65,  41,  42,  47, 115, 101,  75,  25, 109,  38,  66,
             55,  13,  67, 104,  95,  53,  83,  98, 116,  12, 102,   3, 111,
            103,  23,  49,  70,  88, 100,  43,   9,   1,  36,  71,  28,  85,
            106,  63,  52,  56,  32,  26,  69,  10,  21,  89,  17, 108,  91,
             31,  45],
           dtype='int64')

In [40]:
for col in requied_cols:
    for enum in indixes:
        if np.isnan(train_data[col][enum]):
            if train_data["Target"][enum] == 'о':
                train_data[col][enum] = ppp[col][0]
            else:
                train_data[col][enum] = ppp[col][1]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [41]:
train_data.isnull().any()

Number                           False
Глюкоза                          False
Мочевина                         False
Креатинин                        False
Мочевая к-та                     False
Холестерин                       False
Х-ЛПВП                           False
Х-ЛПНП                           False
Триглицериды                     False
индекс массы тела                False
smoking                          False
Alcoholic                        False
excess_salt_consumption          False
гиподинамия                      False
стресс                           False
прием п\щ контрац                False
насл отяг, По ГБ,                False
насл отяг, По ССЗ                False
насл отяг, По СД                 False
насл, Отяг по почечн, Заб        False
САД                              False
ДАД                              False
ГЛЖ ин Соколова-Лайона           False
S100b, нг/л (N до 90)            False
Анг II, пг/мл (N 10-60 пг/мл)    False
ЭТ, пмоль/л    (N =0,09) 

In [42]:
train_data.drop(columns={"Target"}, inplace=True)

In [43]:
test_target[np.where(test_target == 'п')] = 1

In [44]:
test_target[np.where(test_target == 'о')] = 0

In [45]:
train_target[np.where(train_target == 'п')] = 1

In [46]:
train_target[np.where(train_target == 'о')] = 0

In [47]:
test_target = test_target.astype(int)
train_target = train_target.astype(int)

In [57]:
test_target

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1])

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
forest = RandomForestClassifier(n_estimators = 100, n_jobs = -1)

In [50]:
forest.fit(train_data, train_target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [51]:
result = forest.predict(test_data.fillna(0))

In [60]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score

In [58]:
roc_auc_score(test_target, result)

0.75

In [61]:
precision_score(test_target, result)

0.5882352941176471

In [69]:
new_train = (train_data - train_data.mean()) / train_data.std()

In [70]:
new_test = (test_data - test_data.mean()) / test_data.std()

In [71]:
forest.fit(new_train, train_target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [73]:
result_norm = forest.predict(new_test.fillna(0))

In [74]:
roc_auc_score(test_target, result_norm)

0.7

In [75]:
precision_score(test_target, result_norm)

1.0

In [77]:
result_norm

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0])

In [78]:
test_target

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1])

In [62]:
from sklearn.ensemble import GradientBoostingClassifier

In [63]:
grad = GradientBoostingClassifier(n_estimators=100)

In [64]:
grad.fit(train_data, train_target)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [66]:
result_grad = grad.predict(test_data.fillna(0))

In [67]:
roc_auc_score(test_target, result_grad)

0.6785714285714286

In [68]:
precision_score(test_target, result_grad)

0.5263157894736842

In [62]:
cols = test_data.columns[test_data.isnull().any()]

In [63]:
cols

Index(['ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24'],
      dtype='object')

In [69]:
means = np.array(train_data[cols].mean())

In [70]:
inds = test_data.index
inds

Int64Index([ 57,   4,  90,  29,   8,  24,  72,  22,  82,  30,  74,  62,  44,
             84,  77,  14, 113, 117,  51,   2,  97,   6,  39, 112],
           dtype='int64')

In [74]:
for enum, col in enumerate(cols):
    for ind in inds:
        if np.isnan(test_data[col][ind]):
            test_data[col][ind] = means[enum]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [76]:
forest.fit(train_data, train_target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [77]:
result_means = forest.predict(test_data)

In [78]:
roc_auc_score(test_target, result_means)

0.65

In [47]:
from sklearn.ensemble import RandomForestRegressor

In [48]:
forest = RandomForestRegressor(n_estimators=100, n_jobs=-1)

In [65]:
forest.fit(train_data.drop(columns=requied_cols), train_data["HLDF (нг/мл"])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [66]:
res = forest.predict(test_data.drop(columns=requied_cols))

In [67]:
arr = np.array(test_data["HLDF (нг/мл"])

In [68]:
test = np.array(test_target)

In [69]:
for i in range(res.__len__()):
    print(res[i], arr[i], test[i])

58.5323076923077 93.0 о
71.65564102564107 nan о
60.49564102564105 nan п
114.63153846153851 nan о
74.74974358974362 130.0 о
111.84564102564107 nan о
81.50743589743594 53.0 п
109.3328205128206 nan о
81.9225641025642 nan п
99.86435897435904 nan о
76.94000000000007 nan п
63.42358974358978 90.0 о
91.12000000000008 nan о
100.85871794871795 47.0 п
68.9138461538462 56.0 п
80.5664102564103 112.0 о
63.35820512820519 55.0 п
66.95487179487185 nan п
103.7325641025642 nan о
77.0828205128206 nan о
104.05717948717955 nan п
71.41948717948722 102.0 о
99.18025641025646 nan о
63.19179487179492 nan п


In [46]:
cols = test_data.columns[test_data.isnull().any()]

In [58]:
cols = cols.delete(5)

In [59]:
cols

Index(['ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'АТ к S100b', 'АТ к Анг  II ', 'АТ к ЭТ ',
       'АТ к HLDF- 24'],
      dtype='object')

In [69]:
means = np.array(train_data[cols].mean())

In [72]:
inds = test_data.index
inds

Int64Index([ 57,   4,  90,  29,   8,  24,  72,  22,  82,  30,  74,  62,  44,
             84,  77,  14, 113, 117,  51,   2,  97,   6,  39, 112],
           dtype='int64')

In [74]:
for enum, col in enumerate(cols):
    for ind in inds:
        if np.isnan(test_data[col][ind]):
            test_data[col][ind] = means[enum]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [76]:
test_data.isnull().any()

Number                           False
Глюкоза                          False
Мочевина                         False
Креатинин                        False
Мочевая к-та                     False
Холестерин                       False
Х-ЛПВП                           False
Х-ЛПНП                           False
Триглицериды                     False
индекс массы тела                False
smoking                          False
Alcoholic                        False
excess_salt_consumption          False
гиподинамия                      False
стресс                           False
прием п\щ контрац                False
насл отяг, По ГБ,                False
насл отяг, По ССЗ                False
насл отяг, По СД                 False
насл, Отяг по почечн, Заб        False
САД                              False
ДАД                              False
ГЛЖ ин Соколова-Лайона           False
S100b, нг/л (N до 90)            False
Анг II, пг/мл (N 10-60 пг/мл)    False
ЭТ, пмоль/л    (N =0,09) 

In [43]:
~np.isnan(test_data["HLDF (нг/мл"])

57      True
4      False
90     False
29     False
8       True
24     False
72      True
22     False
82     False
30     False
74     False
62      True
44     False
84      True
77      True
14      True
113     True
117    False
51     False
2      False
97     False
6       True
39     False
112    False
Name: HLDF (нг/мл, dtype: bool

In [44]:
test_data["HLDF (нг/мл"].index.__len__()

24

In [45]:
ind = test_data["HLDF (нг/мл"].index[~np.isnan(test_data["HLDF (нг/мл"])]
anti_ind = test_data["HLDF (нг/мл"].index[np.isnan(test_data["HLDF (нг/мл"])]

In [46]:
test_data.loc[ind] 

Number  Глюкоза  Мочевина  Креатинин  Мочевая к-та  Холестерин  Х-ЛПВП  \
57    116.0     15.8       3.6         84           312         4.1    1.35   
8      20.0      7.1       5.3         93           478         4.0    0.53   
72     31.0      6.1       4.8         96           498         7.4    1.59   
62    131.0      5.2       8.8         98           349         3.7    1.25   
84     71.0      6.7       6.5         88           386         5.7    2.27   
77     47.0      6.3       5.4         76           575         7.0    1.52   
14     29.0      6.7       6.7         87           326         5.5    1.59   
113   134.0      5.3       6.5         73           366         4.9    1.73   
6      15.0     11.7       3.2         66           434         6.8    0.92   

     Х-ЛПНП  Триглицериды  индекс массы тела  ...  female  no_spec_gender  \
57     1.91          3.22              27.87  ...       0               0   
8      1.73          4.41              41.03  ...       0               1   
72     4.39          3.73              33.02  ...       0               0   
62     2.45          0.73              28.08  ...       0               0   
84     3.27          0.54              27.12  ...       1               0   
77     4.75          1.72              38.74  ...       0               0   
14     3.04          0.75              26.64  ...       0               0   
113    3.14          0.75              26.47  ...       0               0   
6      4.59          4.65              40.20  ...       1               0   

     laborers  servants  leadership  scientific  engineering  no_job_data  \
57          1         0           0           0            0            0   
8           1         0           0           0            0            0   
72          0         0           0           0            1            0   
62          0         0           0           0            0            1   
84          0         1           0           0            0            0   
77          1         0           0           0            0            0   
14          0         0           0           0            1            0   
113         0         0           0           0            1            0   
6           1         0           0           0            0            0   

     retiree   age  
57         0  54.0  
8          0  57.0  
72         0  47.0  
62         0  29.0  
84         0  58.0  
77         0  55.0  
14         0  57.0  
113        0  30.0  
6          0  53.0  

[9 rows x 43 columns]

In [82]:
new_train_data = train_data.append(test_data.loc[ind])

In [83]:
new_train_target = np.array(new_train_data["HLDF (нг/мл"])

In [84]:
new_train_target

array([ 57.66666667, 120.        , 108.23076923,  57.66666667,
        56.        ,  57.66666667,  54.        , 108.23076923,
       108.23076923,  62.        , 108.23076923, 108.23076923,
        57.66666667,  57.66666667, 118.        ,  57.66666667,
        57.66666667,  64.        , 108.23076923,  57.66666667,
       124.        , 108.23076923, 108.23076923, 108.23076923,
       105.        , 129.        ,  62.        ,  70.        ,
        80.        ,  84.        , 115.        ,  97.        ,
        57.66666667,  59.        ,  57.66666667, 105.        ,
        57.66666667, 108.23076923, 106.        ,  57.66666667,
       108.23076923, 108.23076923,  88.        , 108.23076923,
       108.23076923,  57.66666667,  57.66666667,  54.        ,
       118.        ,  57.66666667, 108.23076923, 108.23076923,
       108.23076923,  91.        , 108.23076923,  57.66666667,
        64.        , 118.        ,  50.        ,  57.66666667,
        57.66666667, 110.        ,  57.66666667, 108.23

In [85]:
new_test_data = test_data.loc[anti_ind]

In [86]:
from sklearn.ensemble import RandomForestRegressor

In [87]:
forest = RandomForestRegressor(n_estimators = 100, n_jobs = -1)

In [88]:
forest_train = np.array(new_train_data.drop(columns={"HLDF (нг/мл"}).fillna(0))

In [89]:
forest.fit(forest_train, new_train_target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [63]:
requied_cols

Index(['ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24'],
      dtype='object')

In [64]:
forest_test = np.array(new_test_data.drop(columns=requied_cols).fillna(0))

NameError: name 'new_test_data' is not defined

In [91]:
res = forest.predict(forest_test)

In [92]:
res

array([80.48358974, 90.50512821, 99.56076923, 86.73230769, 98.78897436,
       83.0074359 , 85.08025641, 92.94307692, 84.14564103, 81.42641026,
       83.86717949, 81.34307692, 85.30923077, 83.43820513, 82.06384615])

In [93]:
true= np.array(data.loc[anti_ind]["Target"])

In [94]:
for i in range(res.__len__()):
    print(res[i], true[i])

80.48358974358976 о
90.50512820512824 п
99.56076923076925 о
86.73230769230776 о
98.78897435897436 о
83.00743589743595 п
85.08025641025647 о
92.94307692307693 п
84.14564102564108 о
81.42641025641032 п
83.86717948717957 о
81.34307692307698 о
85.30923076923084 п
83.4382051282052 о
82.06384615384621 п


In [219]:
extra_train_data = new_train_data.drop(columns = new_train_data.columns[new_train_data.isnull().any()])

In [222]:
extra_test_data = new_test_data.drop(columns = new_train_data.columns[new_train_data.isnull().any()])

In [223]:
forest.fit(extra_train_data.drop(columns = {"HLDF (нг/мл"}), new_train_target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [224]:
res_2 = forest.predict(extra_test_data.drop(columns = {"HLDF (нг/мл"}))

In [70]:
for i in range(res.__len__()):
    print(res[i], true[i])

NameError: name 'true' is not defined

In [121]:
test_data.columns

Index(['Number', 'Глюкоза', 'Мочевина', 'Креатинин', 'Мочевая к-та',
       'Холестерин', 'Х-ЛПВП', 'Х-ЛПНП', 'Триглицериды', 'индекс массы тела',
       'smoking', 'Alcoholic', 'excess_salt_consumption', 'гиподинамия',
       'стресс', 'прием п\щ контрац', 'насл отяг, По ГБ, ',
       'насл отяг, По ССЗ', 'насл отяг, По СД', 'насл, Отяг по почечн, Заб',
       'САД', 'ДАД', 'ГЛЖ ин Соколова-Лайона', 'S100b, нг/л (N до 90)',
       'Анг II, пг/мл (N 10-60 пг/мл)', 'ЭТ, пмоль/л    (N =0,09)',
       'VEGF,  пг/мл (N40-600)', 'HLDF (нг/мл', 'АТ к S100b', 'АТ к Анг  II ',
       'АТ к ЭТ ', 'АТ к HLDF- 24', 'male', 'female', 'no_spec_gender',
       'laborers', 'servants', 'leadership', 'scientific', 'engineering',
       'no_job_data', 'retiree', 'age'],
      dtype='object')

In [62]:
rep_arr = test_data["HLDF (нг/мл"]

In [63]:
rep_arr[anti_ind] = res

In [64]:
rep_arr

57      93.000
4       79.803
90      65.351
29     106.920
8      130.000
24     106.279
72      53.000
22     104.017
82      74.670
30      99.409
74      84.654
62      90.000
44     101.803
84      47.000
77      56.000
14     112.000
113     55.000
117     71.381
51     101.315
2       77.362
97     103.301
6      102.000
39      93.543
112     62.898
Name: HLDF (нг/мл, dtype: float64

In [65]:
test_data["HLDF (нг/мл"] = rep_arr

In [66]:
requied_cols = train_data.columns[train_data.isnull().any()]

In [67]:
train_data["Target"] = train_target

In [68]:
ppp = train_data.groupby("Target", as_index = False)[requied_cols].mean()
ppp

Target  ГЛЖ ин Соколова-Лайона  S100b, нг/л (N до 90)  \
0      о               26.312500              65.876000   
1      п               26.552632              59.704667   

   Анг II, пг/мл (N 10-60 пг/мл)  ЭТ, пмоль/л    (N =0,09)  \
0                     319.126207                  0.641724   
1                      23.560000                  0.692667   

   VEGF,  пг/мл (N40-600)  АТ к S100b  АТ к Анг  II     АТ к ЭТ   \
0              258.035172  405.172414     331.034483  225.862069   
1              444.646667  583.333333     366.666667  286.666667   

   АТ к HLDF- 24  
0      91.379310  
1     103.333333

In [69]:
indixes = train_data.index
indixes

Int64Index([ 73,   5,  46, 114,  79,  86,  99,  37,  27,  80,  59,  60,  94,
             68,  15,  81, 110, 105,  18,  93,   7,  34,  19,  35,  50,  16,
             92,  48,  58,  11,  20,  61,  78,  96,  76,  54, 107,  40,  33,
             87,  64,  65,  41,  42,  47, 115, 101,  75,  25, 109,  38,  66,
             55,  13,  67, 104,  95,  53,  83,  98, 116,  12, 102,   3, 111,
            103,  23,  49,  70,  88, 100,  43,   9,   1,  36,  71,  28,  85,
            106,  63,  52,  56,  32,  26,  69,  10,  21,  89,  17, 108,  91,
             31,  45],
           dtype='int64')

In [71]:
for col in requied_cols:
    for enum in indixes:
        if np.isnan(train_data[col][enum]):
            if train_data["Target"][enum] == 'о':
                train_data[col][enum] = ppp[col][0]
            else:
                train_data[col][enum] = ppp[col][1]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [72]:
train_data.isnull().any()

Number                           False
Глюкоза                          False
Мочевина                         False
Креатинин                        False
Мочевая к-та                     False
Холестерин                       False
Х-ЛПВП                           False
Х-ЛПНП                           False
Триглицериды                     False
индекс массы тела                False
smoking                          False
Alcoholic                        False
excess_salt_consumption          False
гиподинамия                      False
стресс                           False
прием п\щ контрац                False
насл отяг, По ГБ,                False
насл отяг, По ССЗ                False
насл отяг, По СД                 False
насл, Отяг по почечн, Заб        False
САД                              False
ДАД                              False
ГЛЖ ин Соколова-Лайона           False
S100b, нг/л (N до 90)            False
Анг II, пг/мл (N 10-60 пг/мл)    False
ЭТ, пмоль/л    (N =0,09) 

In [77]:
new_train_data = train_data

Number                           False
Глюкоза                          False
Мочевина                         False
Креатинин                        False
Мочевая к-та                     False
Холестерин                       False
Х-ЛПВП                           False
Х-ЛПНП                           False
Триглицериды                     False
индекс массы тела                False
smoking                          False
Alcoholic                        False
excess_salt_consumption          False
гиподинамия                      False
стресс                           False
прием п\щ контрац                False
насл отяг, По ГБ,                False
насл отяг, По ССЗ                False
насл отяг, По СД                 False
насл, Отяг по почечн, Заб        False
САД                              False
ДАД                              False
ГЛЖ ин Соколова-Лайона            True
S100b, нг/л (N до 90)             True
Анг II, пг/мл (N 10-60 пг/мл)     True
ЭТ, пмоль/л    (N =0,09) 