In [1]:
import numpy as np
import pandas as pd

In [2]:
from random import shuffle

In [3]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [177]:
train_1 = pd.read_excel("train1.xlsx")
train_2 = pd.read_excel("train2.xlsx")
train_3 = pd.read_excel("train3.xlsx")
train_4 = pd.read_excel("train4.xlsx")

### Сравним колонки данных

In [178]:
cols_1 = train_1.columns
cols_2 = train_2.columns
cols_3 = train_3.columns
cols_4 = train_4.columns

In [179]:
cols_4.__len__()

89

In [180]:
np.unique(cols_1 == cols_2)

array([ True])

In [181]:
np.unique(cols_2 == cols_3)

array([ True])

In [182]:
np.unique(cols_3 == cols_4)

array([ True])

### Рассмотрим данные

In [183]:
train_1.head(4)

noma  im  ecg_id  sys  MB0  MB1  MB2  MSEP  MSRP  MDP  ...     msh22  \
0    26   1   45909  120    0    0   -1     0     0    0  ...  6.987262   
1    35   1   46125  120  251  176  343   280   373  551  ...  6.604633   
2    36   1   46153  120    0    0   -1     0     0    0  ...  7.617065   
3    39   1   46221  118    0    0   -1     0     0    0  ...  6.729358   

      msh23     msh24     msh25     msh26     msh27     msh28     msh29  \
0  5.842897  6.949771  5.843638  6.935230  5.821854  6.910798  5.806775   
1  5.460614  6.555808  5.436133  6.521528  5.415350  6.498449  5.406096   
2  6.454835  7.626573  6.351499  7.605313  6.365222  7.579783  6.367527   
3  5.666262  6.690083  5.614659  6.655641  5.615052  6.642894  5.576259   

      msh30     msh31  
0  6.897684  5.639776  
1  6.486808  5.397264  
2  7.572513  5.750414  
3  6.636607  5.491374  

[4 rows x 89 columns]

In [184]:
train_2.head(4)

noma  im  ecg_id  sys  MB0  MB1  MB2  MSEP  MSRP  MDP  ...     msh22  \
0    26   1   45909  120    0    0   -1     0     0    0  ...  6.987262   
1    35   1   46125  120  251  176  343   280   373  551  ...  6.604633   
2    36   1   46153  120    0    0   -1     0     0    0  ...  7.617065   
3    39   1   46221  118    0    0   -1     0     0    0  ...  6.729358   

      msh23     msh24     msh25     msh26     msh27     msh28     msh29  \
0  5.842897  6.949771  5.843638  6.935230  5.821854  6.910798  5.806775   
1  5.460614  6.555808  5.436133  6.521528  5.415350  6.498449  5.406096   
2  6.454835  7.626573  6.351499  7.605313  6.365222  7.579783  6.367527   
3  5.666262  6.690083  5.614659  6.655641  5.615052  6.642894  5.576259   

      msh30     msh31  
0  6.897684  5.639776  
1  6.486808  5.397264  
2  7.572513  5.750414  
3  6.636607  5.491374  

[4 rows x 89 columns]

In [185]:
train_3.head(4)

noma  im  ecg_id  sys  MB0  MB1  MB2  MSEP  MSRP  MDP  ...     msh22  \
0    61   1   46522  106  254  179  349   292   378  545  ...  6.660123   
1    90   1   46886  110  197  144  303   224   382  488  ...  6.726418   
2   270   1   48578  109  234  154  339   297   408  565  ...  6.641700   
3   303   1   48781  109  222  152  326   280   402  536  ...  6.627093   

      msh23     msh24     msh25     msh26     msh27     msh28     msh29  \
0  5.549093  6.618528  5.510096  6.582642  5.501579  6.556057  5.493603   
1  5.660824  6.682837  5.641838  6.650321  5.628031  6.628800  5.622539   
2  5.600142  6.592924  5.576515  6.558969  5.564669  6.538046  5.557355   
3  5.542434  6.584295  5.513868  6.550703  5.493273  6.527643  5.489903   

      msh30     msh31  
0  6.540355  5.468881  
1  6.617181  5.617567  
2  6.521370  5.559598  
3  6.514030  5.490624  

[4 rows x 89 columns]

In [186]:
train_4.head(4)

noma  im  ecg_id  sys  MB0  MB1  MB2  MSEP  MSRP  MDP  ...     msh22  \
0    20   1   43663  125  236  163  289   267   405  545  ...  6.502965   
1    24   1   44834  124  304  239  406   331   468  607  ...  6.738291   
2    25   1   44894  121    0    0   -1     0     0    0  ...  6.826538   
3    26   1   45909  120    0    0   -1     0     0    0  ...  6.987262   

      msh23     msh24     msh25     msh26     msh27     msh28     msh29  \
0  5.206837  6.451523  5.185361  6.413278  5.173160  6.388229  5.165759   
1  5.349472  6.694669  5.332950  6.660459  5.313581  6.639714  5.308578   
2  5.390181  6.789557  5.362098  6.761636  5.343485  6.734811  5.338540   
3  5.842897  6.949771  5.843638  6.935230  5.821854  6.910798  5.806775   

      msh30     msh31  
0  6.376049  5.161985  
1  6.628854  5.302648  
2  6.723019  5.251142  
3  6.897684  5.639776  

[4 rows x 89 columns]

In [187]:
dupes_2 = []
dupes_3 = []
dupes_4 = []

for j in range(train_1.__len__()):
    
    first_item = np.array(train_1.loc[j])
    
    #print("Item num ", j)

    for i in range(train_2.__len__()):
        sec_item = np.array(train_2.loc[i])

        if np.allclose(first_item, sec_item):
            #print("Second ", i)
            dupes_2.append(i)

    for i in range(train_3.__len__()):
        thir_item = np.array(train_3.loc[i])

        if np.allclose(first_item, thir_item):
            #print("Third ", i)
            dupes_3.append(i)

    for i in range(train_4.__len__()):
        fort_item = np.array(train_4.loc[i])

        if np.allclose(first_item, fort_item):
            #print("Forth ", i)
            dupes_4.append(i)

KeyboardInterrupt: 

In [188]:
train_1.__len__(), dupes_2.__len__(), dupes_3.__len__(), dupes_4.__len__()

(485, 7, 0, 6)

## Подбор параметров:

In [189]:
np.unique(train_4.dtypes)

array([dtype('int64'), dtype('float64')], dtype=object)

In [190]:
np.array(train_4.isna().sum())

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [191]:
data = pd.DataFrame.copy(train_4)

In [192]:
target = np.array(data['im'])

In [193]:
data.drop(columns = 'im', inplace=True)

### Разобьём на тестовую и тренировочную части:

In [194]:
from sklearn.model_selection import train_test_split

In [195]:
X_train, X_test, y_train, y_test = train_test_split(pd.DataFrame.copy(data), np.copy(target), 
                                                   test_size = 0.2,
                                                   random_state = 451)

In [196]:
X_train = (X_train - X_train.mean()) / X_train.std()

In [197]:
X_test = (X_test - X_test.mean()) / X_test.std()

In [198]:
from catboost import CatBoostClassifier

In [199]:
model = CatBoostClassifier(logging_level='Silent')

Изначальная оценка качества

In [200]:
model.fit(X_train, y_train)

In [201]:
preds = model.predict_proba(X_test)

In [202]:
roc_auc_score(y_test, preds[:, 1])

1.0

Что-то тут не так. методом подбора было получено, что параметр sys дает качество работы 1.0. Удалю его

In [203]:
X_train.drop(columns = 'sys', inplace = True)
X_test.drop(columns = 'sys', inplace = True)

In [204]:
model.fit(X_train, y_train)

In [205]:
preds = model.predict_proba(X_test)[:, 1]

In [206]:
roc_auc_score(y_test, preds)

0.9502801120448179

In [208]:
importance = model.get_feature_importance()

In [211]:
X_train.columns[np.argsort(importance)[::-1]]

Index(['sqrs', 'sst', 'spq', 'MSRP', 'msp1', 'MSEP', 'msp6', 'MdSEP', 'noma',
       'msp3', 'ecg_id', 'quality', 'msh2', 'msp4', 'MDP', 'BR', 'msp2',
       'MdSRP', 'MB0', 'MRR', 'msh0', 'MB1', 'MdDP', 'spqrst', 'msp0', 'msp5',
       'msh3', 'msp7', 'msp29', 'msh25', 'msh5', 'MASEP', 'MSNR', 'msp13',
       'MASRP', 'msp26', 'MPI', 'msp11', 'msp9', 'MAB2', 'msh10', 'msh1',
       'msh28', 'msh11', 'msp14', 'msh16', 'msh22', 'msp8', 'msh27', 'msh13',
       'MADP', 'msh17', 'msh23', 'MB2', 'msp12', 'msh19', 'msh31', 'msp10',
       'msp28', 'msh29', 'msp22', 'msh8', 'msh7', 'msh15', 'msp25', 'msh30',
       'msh12', 'msh9', 'MS5S2', 'msh21', 'msh6', 'msp15', 'msp24', 'msp16',
       'msh4', 'msh26', 'msp20', 'msh14', 'msp21', 'msh24', 'msp18', 'msp23',
       'msh18', 'msp27', 'msp19', 'msp17', 'msh20'],
      dtype='object')

Это уже больше похоже на правду

In [30]:
from sklearn.model_selection import KFold

In [31]:
folds = KFold(n_splits = 4, shuffle = True, random_state = 451)

In [32]:
data = pd.DataFrame.copy(train_4)

In [33]:
values = []

In [34]:
columns = data.drop(columns = ['im', 'sys']).columns

In [35]:
for i in range(100):
    
    model = CatBoostClassifier(logging_level='Silent')
    
    cv = [[], [], [], []]
    cv_true = []
    
    for enum, indixes in enumerate(folds.split(data)):

        train_index = indixes[0]
        test_index = indixes[1]

        train = pd.DataFrame.copy(data.loc[train_index])
        test = pd.DataFrame.copy(data.loc[test_index])

        train_target = np.array(train["im"])
        test_target = np.array(test["im"])

        train.drop(columns = ['im', 'sys'], inplace = True)
        test.drop(columns = ['im', 'sys'], inplace = True)

        model.fit(train, train_target)

        preds = model.predict(test)

        cv_true.append(roc_auc_score(test_target, preds))

        for column in columns:

            hold = np.array(test[column])

            res = np.copy(hold)

            shuffle(res)

            test[column] = res

            preds_shuffle = model.predict(test)

            cv[enum].append(roc_auc_score(test_target, preds_shuffle))

            test[column] = hold
            
    cv_check = [[], [], [], []]
    
    for i in range(4):
        true_i = cv_true[i]

        for enum, val in enumerate(cv[i]):

            if true_i > val:
                cv_check[i].append(enum)
    
    useful_features = []
    
    for item in cv_check:
        for val in item:
            if columns[val] not in useful_features:
                useful_features.append(columns[val])
                
    values.append(useful_features)

In [36]:
values

[['noma',
  'ecg_id',
  'MB0',
  'MB1',
  'MB2',
  'MSRP',
  'MDP',
  'MdSEP',
  'MdSRP',
  'MASEP',
  'quality',
  'spq',
  'sqrs',
  'sst',
  'msp1',
  'msp3',
  'msp4',
  'msp6',
  'msp10',
  'msp12',
  'msp13',
  'msp16',
  'msp20',
  'msp29',
  'msh0',
  'msh1',
  'msh2',
  'msh4',
  'msh8',
  'msh11',
  'msh15',
  'msh27',
  'MdDP',
  'MAB2',
  'BR',
  'msp23',
  'msh10',
  'msh12',
  'msh16',
  'msh18',
  'msh20',
  'msh24',
  'msh26',
  'msh28',
  'msh30',
  'msh31',
  'MSEP',
  'MPI',
  'msp0',
  'msp2',
  'msp5',
  'msp9',
  'msp11',
  'msp14',
  'msp15',
  'msp17',
  'msp21',
  'msp22',
  'msp24',
  'msp25',
  'msp28',
  'msh3',
  'msh9',
  'msh19'],
 ['noma',
  'ecg_id',
  'MB0',
  'MB1',
  'MSEP',
  'MSRP',
  'MDP',
  'MdSRP',
  'MASEP',
  'quality',
  'spq',
  'sqrs',
  'sst',
  'msp1',
  'msp2',
  'msp3',
  'msp4',
  'msp6',
  'msp7',
  'msp10',
  'msp12',
  'msp13',
  'msp18',
  'msp19',
  'msp20',
  'msp21',
  'msp26',
  'msp29',
  'msh0',
  'msh2',
  'msh3',
  'msh6',

In [37]:
association = np.zeros(38)

for enum, item in enumerate(columns):
    print(item)
    for best in values:
        if item in best:
            association[enum] += 1
            
    print(association)

noma
[100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
ecg_id
[100. 100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
MB0
[100. 100.  99.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
MB1
[100. 100.  99.  99.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
MB2
[100. 100.  99.  99.  98.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
MSEP
[

IndexError: index 38 is out of bounds for axis 0 with size 38

In [38]:
order = np.argsort(association)[::-1]

In [39]:
columns[order]

Index(['noma', 'msp1', 'MdSRP', 'MdSEP', 'MDP', 'MSRP', 'quality', 'spq',
       'sqrs', 'sst', 'ecg_id', 'msp3', 'msp4', 'MB1', 'MB0', 'MdDP', 'BR',
       'MSEP', 'MB2', 'msp2', 'msp0', 'msp6', 'spqrst', 'MASEP', 'msp5', 'MRR',
       'msp12', 'msp7', 'msp10', 'msp9', 'msp8', 'MPI', 'MSNR', 'MAB2',
       'msp11', 'MASRP', 'MADP', 'MS5S2'],
      dtype='object')

In [40]:
association[order]

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        99.,  99.,  99.,  99.,  98.,  98.,  98.,  98.,  97.,  97.,  95.,
        92.,  90.,  88.,  88.,  83.,  83.,  75.,  69.,  63.,  63.,  59.,
        45.,  36.,  24.,   5.,   3.])

In [41]:
order.__len__()

38

Мы получили полезные признаки среди данных. Выделим из них те, что имеют значительную степень важности (больше 0.8)

In [66]:
kept_columns = columns[order][association[order] > 80]

In [168]:
kept_columns

Index(['noma', 'msp1', 'MdSRP', 'MdSEP', 'MDP', 'MSRP', 'quality', 'spq',
       'sqrs', 'sst', 'ecg_id', 'msp3', 'msp4', 'MB1', 'MB0', 'MdDP', 'BR',
       'MSEP', 'MB2', 'msp2', 'msp0', 'msp6', 'spqrst', 'MASEP', 'msp5', 'MRR',
       'msp12', 'msp7'],
      dtype='object')

In [68]:
data_kept = data.loc[:, kept_columns]

In [69]:
data_kept

noma      msp1  MdSRP  MdSEP  MDP  MSRP  quality      spq      sqrs  \
0      20 -1.910535    747    746  545   405       50  40.1876   92.2585   
1      24 -1.589506    722    725  607   468       48  26.3349   63.4803   
2      25 -1.330335    723    720    0     0       48  35.0202   83.8203   
3      26 -3.548314    724    721    0     0       49  23.5824   80.0248   
4      28 -3.243341    808    810  554   392       54  38.4733  143.3370   
..    ...       ...    ...    ...  ...   ...      ...      ...       ...   
881  1538 -3.149741    790    792  532   423       89  31.2400  137.9239   
882  1549 -2.825818    802    802    0     0       90  33.6195  132.9423   
883  1550 -2.775345    780    775  552   398       87  43.4442  124.2295   
884  1559 -2.840044    857    857  560   414       97  40.3583  111.5292   
885  1587 -2.667407    969    972  585   457      100  33.2270   88.4053   

          sst  ...  MB2      msp2      msp0      msp6    spqrst     MASEP  \
0    157.8011  ...  289 -1.854945 -2.457549 -1.404692  290.6980   465.777   
1    127.4810  ...  406 -1.535435 -2.143734 -1.077214  217.7738   739.668   
2    266.2422  ...   -1 -1.305276 -1.851782 -1.055835  385.8662     0.000   
3    119.9152  ...   -1 -3.077343 -3.866320 -2.643855  223.7516     0.000   
4     51.0940  ...  355 -2.968844 -4.202455 -1.912119  233.6694   307.113   
..        ...  ...  ...       ...       ...       ...       ...       ...   
881   89.8132  ...  326 -2.297996 -3.859313 -1.686862  259.6793   860.485   
882   81.6738  ...   -1 -2.553076 -3.284682 -1.772262  248.7505     0.000   
883   88.2555  ...  372 -2.685187 -3.631223 -1.555766  256.9504   669.988   
884   41.2635  ...  396 -2.385244 -3.510285 -1.310061  193.8501   559.635   
885   96.2085  ...  413 -1.941661 -3.323564 -1.523573  218.2127  1245.710   

         msp5  MRR     msp12      msp7  
0   -1.425296  746 -0.956841 -1.319339  
1   -1.128756  724 -0.736971 -1.034159  
2   -1.136165    0 -0.651436 -1.033227  
3   -2.687508    0 -2.324076 -2.700362  
4   -1.935366  806 -1.365152 -1.928643  
..        ...  ...       ...       ...  
881 -1.771832  788 -1.271641 -1.744464  
882 -1.711931    0 -1.145977 -1.689161  
883 -1.609726  780 -1.135217 -1.518972  
884 -1.370694  860 -0.934127 -1.328976  
885 -1.527871  972 -1.046931 -1.606046  

[886 rows x 28 columns]

In [70]:
model = CatBoostClassifier(logging_level='Silent')

In [71]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, y_train, y_test = train_test_split(pd.DataFrame.copy(data_kept), 
                                                    target,
                                                    test_size = 0.2,
                                                    random_state = 451)

In [73]:
X_train = (X_train - X_train.mean()) / X_train.std()
X_test = (X_test - X_test.mean()) / X_test.std()

In [74]:
model.fit(X_train, y_train)

In [75]:
preds = model.predict_proba(X_test)

In [76]:
roc_auc_score(y_test, preds[:, 1])

0.958858543417367

Получили повышение качества на почти 1%.

In [125]:
train_4_fin = pd.DataFrame.copy(train_4.loc[:, kept_columns])
train_4_target = train_4['im']

In [135]:
model = CatBoostClassifier(logging_level='Silent', depth = 10, iterations = 3000)

In [136]:
model.fit(train_4_fin, train_4_target)

In [137]:
test_4 = pd.read_excel("recog4.xlsx")

In [138]:
test_4.head(4)

noma  im  ecg_id  sys  MB0  MB1  MB2  MSEP  MSRP  MDP  ...     msh22  \
0  1601   1   53835  124  242  164  337   300   429  568  ...  6.617425   
1  1602   1   53836  108  217  148  269   249   386  514  ...  6.442242   
2  1603   1   53837  108  229  156  273   260   382  513  ...  6.432598   
3  1604   1   53842  122  236  165  319   276   427  567  ...  6.591509   

      msh23     msh24     msh25     msh26     msh27     msh28     msh29  \
0  5.497065  6.569775  5.471414  6.535914  5.457092  6.512985  5.447591   
1  5.234757  6.393759  5.208371  6.357740  5.186381  6.332794  5.170778   
2  5.206867  6.381908  5.181787  6.344087  5.162565  6.318358  5.152116   
3  5.387763  6.542901  5.364574  6.508561  5.348209  6.484356  5.339374   

      msh30     msh31  
0  6.501502  5.440081  
1  6.319686  5.168480  
2  6.306082  5.145070  
3  6.472859  5.334266  

[4 rows x 89 columns]

In [139]:
test_target = np.array(test_4['im'])

In [140]:
test_4 = test_4.loc[:, kept_columns]

In [141]:
test_4.head(1)

noma     msp1  MdSRP  MdSEP  MDP  MSRP  quality      spq     sqrs      sst  \
0  1601 -2.26306    922    918  568   429      100  34.6481  95.0899  90.1575   

   ...  MB2     msp2      msp0      msp6    spqrst    MASEP      msp5  MRR  \
0  ...  337 -1.65057 -3.027304 -1.059823  220.3011  950.155 -1.050731  922   

     msp12      msp7  
0 -0.54662 -1.129308  

[1 rows x 28 columns]

In [142]:
preds_test = model.predict_proba(test_4)[:, 1]

In [143]:
roc_auc_score(test_target, preds_test)

0.8045676161149603

Будем отталкиваться от данного результата

In [144]:
def numeric_features(feat_line):
    
    pre_arr = np.absolute(feat_line[None, :] - feat_line[:, None])
    max_val = pre_arr.max()
    
    return pre_arr / pre_arr.max()

def build_distances(train_line, test_line):
    
    train_pre_arr = np.absolute(train_line[None, :] - train_line[:, None])
    test_pre_arr = np.absolute(train_line[None, :] - test_line[:, None])
    
    train_max = train_pre_arr.max()

    return train_pre_arr / train_max, test_pre_arr / train_max

def recombinate(arr_list, names_list):
    # also uses features and percentiles lists
    
    pairwise = np.zeros(arr_list[0].shape)
    
    for enum, item in enumerate(names_list):
        
        position = np.where(features == item)[0][0]
        pairwise += percentiles[position] / 100 * arr_list[enum]
        
    return pairwise

In [154]:
def recombination(train_df, test_df, features, percentiles, filling_diag = None):
    # пока что уберем из рассмотрения столбец Number, т.к. я не знаю, что с ним делать
    
    columns = train_df.columns
    
    train_len = train_df.__len__()
    test_len = test_df.__len__()
    
    train_pairwise = np.zeros((train_len, train_len))
    test_pairwise = np.zeros((test_len, train_len))
    
    for col in columns:
        
        train_arr = np.array(train_df[col])
        test_arr = np.array(test_df[col])
        
        train_dist, test_dist = build_distances(train_arr, test_arr)
        
        position = np.where(features == col)[0][0]
        
        train_pairwise += percentiles[position] / 100 * train_dist
        test_pairwise += percentiles[position] / 100 * test_dist
        
    return train_pairwise, test_pairwise

In [155]:
train_paired, test_paired = recombination(train_4_fin, test_4, kept_columns, association[order])

In [156]:
train_paired.shape

(886, 886)

In [157]:
test_paired.shape

(523, 886)

In [164]:
model = CatBoostClassifier(logging_level='Silent', depth = 8, iterations = 2000)

In [165]:
model.fit(train_paired, train_4_target)

In [166]:
preds_paired = model.predict_proba(test_paired)[:, 1]

In [167]:
roc_auc_score(test_target, preds_paired)

0.7760841673081859